/* Autogenerated: fiat_crypto.js word-by-word-montgomery p 64 '67*2^194*3^61-1' */
/* curve description: p */
/* machine_wordsize = 64 (from "64") */
/* requested operations: (all) */
/* m = 0x1ae2e77fe01e2639b854da79fe3ffffffffffffffffffffffffffffffffffffffffffffffff (from "67*2^194*3^61-1") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) + (z[4] << 256) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) + (z[4] << 256) in */
/*                            if x1 & (2^320-1) < 2^319 then x1 & (2^320-1) else (x1 & (2^320-1)) - 2^320 */

#include <stdint.h>
typedef unsigned char fiat_p_uint1;
typedef signed char fiat_p_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_P_FIAT_EXTENSION __extension__
#  define FIAT_P_FIAT_INLINE __inline__
#else
#  define FIAT_P_FIAT_EXTENSION
#  define FIAT_P_FIAT_INLINE
#endif

FIAT_P_FIAT_EXTENSION typedef signed __int128 fiat_p_int128;
FIAT_P_FIAT_EXTENSION typedef unsigned __int128 fiat_p_uint128;

/* The type fiat_p_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_p_montgomery_domain_field_element[5];

/* The type fiat_p_non_montgomery_domain_field_element is a field element NOT in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_p_non_montgomery_domain_field_element[5];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_p_addcarryx_u64 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^64
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_p_addcarryx_u64(uint64_t* out1, fiat_p_uint1* out2, fiat_p_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_p_uint128 x1;
  uint64_t x2;
  fiat_p_uint1 x3;
  x1 = ((arg1 + (fiat_p_uint128)arg2) + arg3);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (fiat_p_uint1)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_p_subborrowx_u64 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^64
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
void fiat_p_subborrowx_u64(uint64_t* out1, fiat_p_uint1* out2, fiat_p_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_p_int128 x1;
  fiat_p_int1 x2;
  uint64_t x3;
  x1 = ((arg2 - (fiat_p_int128)arg1) - arg3);
  x2 = (fiat_p_int1)(x1 >> 64);
  x3 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  *out1 = x3;
  *out2 = (fiat_p_uint1)(0x0 - x2);
}

/*
 * The function fiat_p_mulx_u64 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^64
 *   out2 = ⌊arg1 * arg2 / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_p_mulx_u64(uint64_t* out1, uint64_t* out2, uint64_t arg1, uint64_t arg2) {
  fiat_p_uint128 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = ((fiat_p_uint128)arg1 * arg2);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (uint64_t)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_p_cmovznz_u64 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_p_cmovznz_u64(uint64_t* out1, fiat_p_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_p_uint1 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_p_int1)(0x0 - x1) & UINT64_C(0xffffffffffffffff));
  x3 = ((x2 & arg3) | ((~x2) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_p_mul multiplies two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_mul(fiat_p_montgomery_domain_field_element out1, const fiat_p_montgomery_domain_field_element arg1, const fiat_p_montgomery_domain_field_element arg2) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  fiat_p_uint1 x17;
  uint64_t x18;
  fiat_p_uint1 x19;
  uint64_t x20;
  fiat_p_uint1 x21;
  uint64_t x22;
  fiat_p_uint1 x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  uint64_t x32;
  uint64_t x33;
  uint64_t x34;
  uint64_t x35;
  fiat_p_uint1 x36;
  uint64_t x37;
  fiat_p_uint1 x38;
  uint64_t x39;
  fiat_p_uint1 x40;
  uint64_t x41;
  fiat_p_uint1 x42;
  uint64_t x43;
  uint64_t x44;
  fiat_p_uint1 x45;
  uint64_t x46;
  fiat_p_uint1 x47;
  uint64_t x48;
  fiat_p_uint1 x49;
  uint64_t x50;
  fiat_p_uint1 x51;
  uint64_t x52;
  fiat_p_uint1 x53;
  uint64_t x54;
  fiat_p_uint1 x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  uint64_t x63;
  uint64_t x64;
  uint64_t x65;
  uint64_t x66;
  fiat_p_uint1 x67;
  uint64_t x68;
  fiat_p_uint1 x69;
  uint64_t x70;
  fiat_p_uint1 x71;
  uint64_t x72;
  fiat_p_uint1 x73;
  uint64_t x74;
  uint64_t x75;
  fiat_p_uint1 x76;
  uint64_t x77;
  fiat_p_uint1 x78;
  uint64_t x79;
  fiat_p_uint1 x80;
  uint64_t x81;
  fiat_p_uint1 x82;
  uint64_t x83;
  fiat_p_uint1 x84;
  uint64_t x85;
  fiat_p_uint1 x86;
  uint64_t x87;
  uint64_t x88;
  uint64_t x89;
  uint64_t x90;
  uint64_t x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  uint64_t x95;
  uint64_t x96;
  uint64_t x97;
  fiat_p_uint1 x98;
  uint64_t x99;
  fiat_p_uint1 x100;
  uint64_t x101;
  fiat_p_uint1 x102;
  uint64_t x103;
  fiat_p_uint1 x104;
  uint64_t x105;
  uint64_t x106;
  fiat_p_uint1 x107;
  uint64_t x108;
  fiat_p_uint1 x109;
  uint64_t x110;
  fiat_p_uint1 x111;
  uint64_t x112;
  fiat_p_uint1 x113;
  uint64_t x114;
  fiat_p_uint1 x115;
  uint64_t x116;
  fiat_p_uint1 x117;
  uint64_t x118;
  uint64_t x119;
  uint64_t x120;
  uint64_t x121;
  uint64_t x122;
  uint64_t x123;
  uint64_t x124;
  uint64_t x125;
  uint64_t x126;
  uint64_t x127;
  uint64_t x128;
  uint64_t x129;
  fiat_p_uint1 x130;
  uint64_t x131;
  fiat_p_uint1 x132;
  uint64_t x133;
  fiat_p_uint1 x134;
  uint64_t x135;
  fiat_p_uint1 x136;
  uint64_t x137;
  uint64_t x138;
  fiat_p_uint1 x139;
  uint64_t x140;
  fiat_p_uint1 x141;
  uint64_t x142;
  fiat_p_uint1 x143;
  uint64_t x144;
  fiat_p_uint1 x145;
  uint64_t x146;
  fiat_p_uint1 x147;
  uint64_t x148;
  fiat_p_uint1 x149;
  uint64_t x150;
  uint64_t x151;
  uint64_t x152;
  uint64_t x153;
  uint64_t x154;
  uint64_t x155;
  uint64_t x156;
  uint64_t x157;
  uint64_t x158;
  uint64_t x159;
  uint64_t x160;
  fiat_p_uint1 x161;
  uint64_t x162;
  fiat_p_uint1 x163;
  uint64_t x164;
  fiat_p_uint1 x165;
  uint64_t x166;
  fiat_p_uint1 x167;
  uint64_t x168;
  uint64_t x169;
  fiat_p_uint1 x170;
  uint64_t x171;
  fiat_p_uint1 x172;
  uint64_t x173;
  fiat_p_uint1 x174;
  uint64_t x175;
  fiat_p_uint1 x176;
  uint64_t x177;
  fiat_p_uint1 x178;
  uint64_t x179;
  fiat_p_uint1 x180;
  uint64_t x181;
  uint64_t x182;
  uint64_t x183;
  uint64_t x184;
  uint64_t x185;
  uint64_t x186;
  uint64_t x187;
  uint64_t x188;
  uint64_t x189;
  uint64_t x190;
  uint64_t x191;
  uint64_t x192;
  fiat_p_uint1 x193;
  uint64_t x194;
  fiat_p_uint1 x195;
  uint64_t x196;
  fiat_p_uint1 x197;
  uint64_t x198;
  fiat_p_uint1 x199;
  uint64_t x200;
  uint64_t x201;
  fiat_p_uint1 x202;
  uint64_t x203;
  fiat_p_uint1 x204;
  uint64_t x205;
  fiat_p_uint1 x206;
  uint64_t x207;
  fiat_p_uint1 x208;
  uint64_t x209;
  fiat_p_uint1 x210;
  uint64_t x211;
  fiat_p_uint1 x212;
  uint64_t x213;
  uint64_t x214;
  uint64_t x215;
  uint64_t x216;
  uint64_t x217;
  uint64_t x218;
  uint64_t x219;
  uint64_t x220;
  uint64_t x221;
  uint64_t x222;
  uint64_t x223;
  fiat_p_uint1 x224;
  uint64_t x225;
  fiat_p_uint1 x226;
  uint64_t x227;
  fiat_p_uint1 x228;
  uint64_t x229;
  fiat_p_uint1 x230;
  uint64_t x231;
  uint64_t x232;
  fiat_p_uint1 x233;
  uint64_t x234;
  fiat_p_uint1 x235;
  uint64_t x236;
  fiat_p_uint1 x237;
  uint64_t x238;
  fiat_p_uint1 x239;
  uint64_t x240;
  fiat_p_uint1 x241;
  uint64_t x242;
  fiat_p_uint1 x243;
  uint64_t x244;
  uint64_t x245;
  uint64_t x246;
  uint64_t x247;
  uint64_t x248;
  uint64_t x249;
  uint64_t x250;
  uint64_t x251;
  uint64_t x252;
  uint64_t x253;
  uint64_t x254;
  uint64_t x255;
  fiat_p_uint1 x256;
  uint64_t x257;
  fiat_p_uint1 x258;
  uint64_t x259;
  fiat_p_uint1 x260;
  uint64_t x261;
  fiat_p_uint1 x262;
  uint64_t x263;
  uint64_t x264;
  fiat_p_uint1 x265;
  uint64_t x266;
  fiat_p_uint1 x267;
  uint64_t x268;
  fiat_p_uint1 x269;
  uint64_t x270;
  fiat_p_uint1 x271;
  uint64_t x272;
  fiat_p_uint1 x273;
  uint64_t x274;
  fiat_p_uint1 x275;
  uint64_t x276;
  uint64_t x277;
  uint64_t x278;
  uint64_t x279;
  uint64_t x280;
  uint64_t x281;
  uint64_t x282;
  uint64_t x283;
  uint64_t x284;
  uint64_t x285;
  uint64_t x286;
  fiat_p_uint1 x287;
  uint64_t x288;
  fiat_p_uint1 x289;
  uint64_t x290;
  fiat_p_uint1 x291;
  uint64_t x292;
  fiat_p_uint1 x293;
  uint64_t x294;
  uint64_t x295;
  fiat_p_uint1 x296;
  uint64_t x297;
  fiat_p_uint1 x298;
  uint64_t x299;
  fiat_p_uint1 x300;
  uint64_t x301;
  fiat_p_uint1 x302;
  uint64_t x303;
  fiat_p_uint1 x304;
  uint64_t x305;
  fiat_p_uint1 x306;
  uint64_t x307;
  uint64_t x308;
  fiat_p_uint1 x309;
  uint64_t x310;
  fiat_p_uint1 x311;
  uint64_t x312;
  fiat_p_uint1 x313;
  uint64_t x314;
  fiat_p_uint1 x315;
  uint64_t x316;
  fiat_p_uint1 x317;
  uint64_t x318;
  fiat_p_uint1 x319;
  uint64_t x320;
  uint64_t x321;
  uint64_t x322;
  uint64_t x323;
  uint64_t x324;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_p_mulx_u64(&x6, &x7, x5, (arg2[4]));
  fiat_p_mulx_u64(&x8, &x9, x5, (arg2[3]));
  fiat_p_mulx_u64(&x10, &x11, x5, (arg2[2]));
  fiat_p_mulx_u64(&x12, &x13, x5, (arg2[1]));
  fiat_p_mulx_u64(&x14, &x15, x5, (arg2[0]));
  fiat_p_addcarryx_u64(&x16, &x17, 0x0, x15, x12);
  fiat_p_addcarryx_u64(&x18, &x19, x17, x13, x10);
  fiat_p_addcarryx_u64(&x20, &x21, x19, x11, x8);
  fiat_p_addcarryx_u64(&x22, &x23, x21, x9, x6);
  x24 = (x23 + x7);
  fiat_p_mulx_u64(&x25, &x26, x14, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x27, &x28, x14, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x29, &x30, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x31, &x32, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x33, &x34, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x35, &x36, 0x0, x34, x31);
  fiat_p_addcarryx_u64(&x37, &x38, x36, x32, x29);
  fiat_p_addcarryx_u64(&x39, &x40, x38, x30, x27);
  fiat_p_addcarryx_u64(&x41, &x42, x40, x28, x25);
  x43 = (x42 + x26);
  fiat_p_addcarryx_u64(&x44, &x45, 0x0, x14, x33);
  fiat_p_addcarryx_u64(&x46, &x47, x45, x16, x35);
  fiat_p_addcarryx_u64(&x48, &x49, x47, x18, x37);
  fiat_p_addcarryx_u64(&x50, &x51, x49, x20, x39);
  fiat_p_addcarryx_u64(&x52, &x53, x51, x22, x41);
  fiat_p_addcarryx_u64(&x54, &x55, x53, x24, x43);
  fiat_p_mulx_u64(&x56, &x57, x1, (arg2[4]));
  fiat_p_mulx_u64(&x58, &x59, x1, (arg2[3]));
  fiat_p_mulx_u64(&x60, &x61, x1, (arg2[2]));
  fiat_p_mulx_u64(&x62, &x63, x1, (arg2[1]));
  fiat_p_mulx_u64(&x64, &x65, x1, (arg2[0]));
  fiat_p_addcarryx_u64(&x66, &x67, 0x0, x65, x62);
  fiat_p_addcarryx_u64(&x68, &x69, x67, x63, x60);
  fiat_p_addcarryx_u64(&x70, &x71, x69, x61, x58);
  fiat_p_addcarryx_u64(&x72, &x73, x71, x59, x56);
  x74 = (x73 + x57);
  fiat_p_addcarryx_u64(&x75, &x76, 0x0, x46, x64);
  fiat_p_addcarryx_u64(&x77, &x78, x76, x48, x66);
  fiat_p_addcarryx_u64(&x79, &x80, x78, x50, x68);
  fiat_p_addcarryx_u64(&x81, &x82, x80, x52, x70);
  fiat_p_addcarryx_u64(&x83, &x84, x82, x54, x72);
  fiat_p_addcarryx_u64(&x85, &x86, x84, x55, x74);
  fiat_p_mulx_u64(&x87, &x88, x75, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x89, &x90, x75, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x91, &x92, x75, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x93, &x94, x75, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x95, &x96, x75, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x97, &x98, 0x0, x96, x93);
  fiat_p_addcarryx_u64(&x99, &x100, x98, x94, x91);
  fiat_p_addcarryx_u64(&x101, &x102, x100, x92, x89);
  fiat_p_addcarryx_u64(&x103, &x104, x102, x90, x87);
  x105 = (x104 + x88);
  fiat_p_addcarryx_u64(&x106, &x107, 0x0, x75, x95);
  fiat_p_addcarryx_u64(&x108, &x109, x107, x77, x97);
  fiat_p_addcarryx_u64(&x110, &x111, x109, x79, x99);
  fiat_p_addcarryx_u64(&x112, &x113, x111, x81, x101);
  fiat_p_addcarryx_u64(&x114, &x115, x113, x83, x103);
  fiat_p_addcarryx_u64(&x116, &x117, x115, x85, x105);
  x118 = ((uint64_t)x117 + x86);
  fiat_p_mulx_u64(&x119, &x120, x2, (arg2[4]));
  fiat_p_mulx_u64(&x121, &x122, x2, (arg2[3]));
  fiat_p_mulx_u64(&x123, &x124, x2, (arg2[2]));
  fiat_p_mulx_u64(&x125, &x126, x2, (arg2[1]));
  fiat_p_mulx_u64(&x127, &x128, x2, (arg2[0]));
  fiat_p_addcarryx_u64(&x129, &x130, 0x0, x128, x125);
  fiat_p_addcarryx_u64(&x131, &x132, x130, x126, x123);
  fiat_p_addcarryx_u64(&x133, &x134, x132, x124, x121);
  fiat_p_addcarryx_u64(&x135, &x136, x134, x122, x119);
  x137 = (x136 + x120);
  fiat_p_addcarryx_u64(&x138, &x139, 0x0, x108, x127);
  fiat_p_addcarryx_u64(&x140, &x141, x139, x110, x129);
  fiat_p_addcarryx_u64(&x142, &x143, x141, x112, x131);
  fiat_p_addcarryx_u64(&x144, &x145, x143, x114, x133);
  fiat_p_addcarryx_u64(&x146, &x147, x145, x116, x135);
  fiat_p_addcarryx_u64(&x148, &x149, x147, x118, x137);
  fiat_p_mulx_u64(&x150, &x151, x138, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x152, &x153, x138, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x154, &x155, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x156, &x157, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x158, &x159, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x160, &x161, 0x0, x159, x156);
  fiat_p_addcarryx_u64(&x162, &x163, x161, x157, x154);
  fiat_p_addcarryx_u64(&x164, &x165, x163, x155, x152);
  fiat_p_addcarryx_u64(&x166, &x167, x165, x153, x150);
  x168 = (x167 + x151);
  fiat_p_addcarryx_u64(&x169, &x170, 0x0, x138, x158);
  fiat_p_addcarryx_u64(&x171, &x172, x170, x140, x160);
  fiat_p_addcarryx_u64(&x173, &x174, x172, x142, x162);
  fiat_p_addcarryx_u64(&x175, &x176, x174, x144, x164);
  fiat_p_addcarryx_u64(&x177, &x178, x176, x146, x166);
  fiat_p_addcarryx_u64(&x179, &x180, x178, x148, x168);
  x181 = ((uint64_t)x180 + x149);
  fiat_p_mulx_u64(&x182, &x183, x3, (arg2[4]));
  fiat_p_mulx_u64(&x184, &x185, x3, (arg2[3]));
  fiat_p_mulx_u64(&x186, &x187, x3, (arg2[2]));
  fiat_p_mulx_u64(&x188, &x189, x3, (arg2[1]));
  fiat_p_mulx_u64(&x190, &x191, x3, (arg2[0]));
  fiat_p_addcarryx_u64(&x192, &x193, 0x0, x191, x188);
  fiat_p_addcarryx_u64(&x194, &x195, x193, x189, x186);
  fiat_p_addcarryx_u64(&x196, &x197, x195, x187, x184);
  fiat_p_addcarryx_u64(&x198, &x199, x197, x185, x182);
  x200 = (x199 + x183);
  fiat_p_addcarryx_u64(&x201, &x202, 0x0, x171, x190);
  fiat_p_addcarryx_u64(&x203, &x204, x202, x173, x192);
  fiat_p_addcarryx_u64(&x205, &x206, x204, x175, x194);
  fiat_p_addcarryx_u64(&x207, &x208, x206, x177, x196);
  fiat_p_addcarryx_u64(&x209, &x210, x208, x179, x198);
  fiat_p_addcarryx_u64(&x211, &x212, x210, x181, x200);
  fiat_p_mulx_u64(&x213, &x214, x201, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x215, &x216, x201, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x217, &x218, x201, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x219, &x220, x201, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x221, &x222, x201, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x223, &x224, 0x0, x222, x219);
  fiat_p_addcarryx_u64(&x225, &x226, x224, x220, x217);
  fiat_p_addcarryx_u64(&x227, &x228, x226, x218, x215);
  fiat_p_addcarryx_u64(&x229, &x230, x228, x216, x213);
  x231 = (x230 + x214);
  fiat_p_addcarryx_u64(&x232, &x233, 0x0, x201, x221);
  fiat_p_addcarryx_u64(&x234, &x235, x233, x203, x223);
  fiat_p_addcarryx_u64(&x236, &x237, x235, x205, x225);
  fiat_p_addcarryx_u64(&x238, &x239, x237, x207, x227);
  fiat_p_addcarryx_u64(&x240, &x241, x239, x209, x229);
  fiat_p_addcarryx_u64(&x242, &x243, x241, x211, x231);
  x244 = ((uint64_t)x243 + x212);
  fiat_p_mulx_u64(&x245, &x246, x4, (arg2[4]));
  fiat_p_mulx_u64(&x247, &x248, x4, (arg2[3]));
  fiat_p_mulx_u64(&x249, &x250, x4, (arg2[2]));
  fiat_p_mulx_u64(&x251, &x252, x4, (arg2[1]));
  fiat_p_mulx_u64(&x253, &x254, x4, (arg2[0]));
  fiat_p_addcarryx_u64(&x255, &x256, 0x0, x254, x251);
  fiat_p_addcarryx_u64(&x257, &x258, x256, x252, x249);
  fiat_p_addcarryx_u64(&x259, &x260, x258, x250, x247);
  fiat_p_addcarryx_u64(&x261, &x262, x260, x248, x245);
  x263 = (x262 + x246);
  fiat_p_addcarryx_u64(&x264, &x265, 0x0, x234, x253);
  fiat_p_addcarryx_u64(&x266, &x267, x265, x236, x255);
  fiat_p_addcarryx_u64(&x268, &x269, x267, x238, x257);
  fiat_p_addcarryx_u64(&x270, &x271, x269, x240, x259);
  fiat_p_addcarryx_u64(&x272, &x273, x271, x242, x261);
  fiat_p_addcarryx_u64(&x274, &x275, x273, x244, x263);
  fiat_p_mulx_u64(&x276, &x277, x264, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x278, &x279, x264, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x280, &x281, x264, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x282, &x283, x264, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x284, &x285, x264, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x286, &x287, 0x0, x285, x282);
  fiat_p_addcarryx_u64(&x288, &x289, x287, x283, x280);
  fiat_p_addcarryx_u64(&x290, &x291, x289, x281, x278);
  fiat_p_addcarryx_u64(&x292, &x293, x291, x279, x276);
  x294 = (x293 + x277);
  fiat_p_addcarryx_u64(&x295, &x296, 0x0, x264, x284);
  fiat_p_addcarryx_u64(&x297, &x298, x296, x266, x286);
  fiat_p_addcarryx_u64(&x299, &x300, x298, x268, x288);
  fiat_p_addcarryx_u64(&x301, &x302, x300, x270, x290);
  fiat_p_addcarryx_u64(&x303, &x304, x302, x272, x292);
  fiat_p_addcarryx_u64(&x305, &x306, x304, x274, x294);
  x307 = ((uint64_t)x306 + x275);
  fiat_p_subborrowx_u64(&x308, &x309, 0x0, x297, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x310, &x311, x309, x299, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x312, &x313, x311, x301, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x314, &x315, x313, x303, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x316, &x317, x315, x305, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x318, &x319, x317, x307, 0x0);
  fiat_p_cmovznz_u64(&x320, x319, x308, x297);
  fiat_p_cmovznz_u64(&x321, x319, x310, x299);
  fiat_p_cmovznz_u64(&x322, x319, x312, x301);
  fiat_p_cmovznz_u64(&x323, x319, x314, x303);
  fiat_p_cmovznz_u64(&x324, x319, x316, x305);
  out1[0] = x320;
  out1[1] = x321;
  out1[2] = x322;
  out1[3] = x323;
  out1[4] = x324;
}

/*
 * The function fiat_p_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_square(fiat_p_montgomery_domain_field_element out1, const fiat_p_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  fiat_p_uint1 x17;
  uint64_t x18;
  fiat_p_uint1 x19;
  uint64_t x20;
  fiat_p_uint1 x21;
  uint64_t x22;
  fiat_p_uint1 x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  uint64_t x32;
  uint64_t x33;
  uint64_t x34;
  uint64_t x35;
  fiat_p_uint1 x36;
  uint64_t x37;
  fiat_p_uint1 x38;
  uint64_t x39;
  fiat_p_uint1 x40;
  uint64_t x41;
  fiat_p_uint1 x42;
  uint64_t x43;
  uint64_t x44;
  fiat_p_uint1 x45;
  uint64_t x46;
  fiat_p_uint1 x47;
  uint64_t x48;
  fiat_p_uint1 x49;
  uint64_t x50;
  fiat_p_uint1 x51;
  uint64_t x52;
  fiat_p_uint1 x53;
  uint64_t x54;
  fiat_p_uint1 x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  uint64_t x63;
  uint64_t x64;
  uint64_t x65;
  uint64_t x66;
  fiat_p_uint1 x67;
  uint64_t x68;
  fiat_p_uint1 x69;
  uint64_t x70;
  fiat_p_uint1 x71;
  uint64_t x72;
  fiat_p_uint1 x73;
  uint64_t x74;
  uint64_t x75;
  fiat_p_uint1 x76;
  uint64_t x77;
  fiat_p_uint1 x78;
  uint64_t x79;
  fiat_p_uint1 x80;
  uint64_t x81;
  fiat_p_uint1 x82;
  uint64_t x83;
  fiat_p_uint1 x84;
  uint64_t x85;
  fiat_p_uint1 x86;
  uint64_t x87;
  uint64_t x88;
  uint64_t x89;
  uint64_t x90;
  uint64_t x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  uint64_t x95;
  uint64_t x96;
  uint64_t x97;
  fiat_p_uint1 x98;
  uint64_t x99;
  fiat_p_uint1 x100;
  uint64_t x101;
  fiat_p_uint1 x102;
  uint64_t x103;
  fiat_p_uint1 x104;
  uint64_t x105;
  uint64_t x106;
  fiat_p_uint1 x107;
  uint64_t x108;
  fiat_p_uint1 x109;
  uint64_t x110;
  fiat_p_uint1 x111;
  uint64_t x112;
  fiat_p_uint1 x113;
  uint64_t x114;
  fiat_p_uint1 x115;
  uint64_t x116;
  fiat_p_uint1 x117;
  uint64_t x118;
  uint64_t x119;
  uint64_t x120;
  uint64_t x121;
  uint64_t x122;
  uint64_t x123;
  uint64_t x124;
  uint64_t x125;
  uint64_t x126;
  uint64_t x127;
  uint64_t x128;
  uint64_t x129;
  fiat_p_uint1 x130;
  uint64_t x131;
  fiat_p_uint1 x132;
  uint64_t x133;
  fiat_p_uint1 x134;
  uint64_t x135;
  fiat_p_uint1 x136;
  uint64_t x137;
  uint64_t x138;
  fiat_p_uint1 x139;
  uint64_t x140;
  fiat_p_uint1 x141;
  uint64_t x142;
  fiat_p_uint1 x143;
  uint64_t x144;
  fiat_p_uint1 x145;
  uint64_t x146;
  fiat_p_uint1 x147;
  uint64_t x148;
  fiat_p_uint1 x149;
  uint64_t x150;
  uint64_t x151;
  uint64_t x152;
  uint64_t x153;
  uint64_t x154;
  uint64_t x155;
  uint64_t x156;
  uint64_t x157;
  uint64_t x158;
  uint64_t x159;
  uint64_t x160;
  fiat_p_uint1 x161;
  uint64_t x162;
  fiat_p_uint1 x163;
  uint64_t x164;
  fiat_p_uint1 x165;
  uint64_t x166;
  fiat_p_uint1 x167;
  uint64_t x168;
  uint64_t x169;
  fiat_p_uint1 x170;
  uint64_t x171;
  fiat_p_uint1 x172;
  uint64_t x173;
  fiat_p_uint1 x174;
  uint64_t x175;
  fiat_p_uint1 x176;
  uint64_t x177;
  fiat_p_uint1 x178;
  uint64_t x179;
  fiat_p_uint1 x180;
  uint64_t x181;
  uint64_t x182;
  uint64_t x183;
  uint64_t x184;
  uint64_t x185;
  uint64_t x186;
  uint64_t x187;
  uint64_t x188;
  uint64_t x189;
  uint64_t x190;
  uint64_t x191;
  uint64_t x192;
  fiat_p_uint1 x193;
  uint64_t x194;
  fiat_p_uint1 x195;
  uint64_t x196;
  fiat_p_uint1 x197;
  uint64_t x198;
  fiat_p_uint1 x199;
  uint64_t x200;
  uint64_t x201;
  fiat_p_uint1 x202;
  uint64_t x203;
  fiat_p_uint1 x204;
  uint64_t x205;
  fiat_p_uint1 x206;
  uint64_t x207;
  fiat_p_uint1 x208;
  uint64_t x209;
  fiat_p_uint1 x210;
  uint64_t x211;
  fiat_p_uint1 x212;
  uint64_t x213;
  uint64_t x214;
  uint64_t x215;
  uint64_t x216;
  uint64_t x217;
  uint64_t x218;
  uint64_t x219;
  uint64_t x220;
  uint64_t x221;
  uint64_t x222;
  uint64_t x223;
  fiat_p_uint1 x224;
  uint64_t x225;
  fiat_p_uint1 x226;
  uint64_t x227;
  fiat_p_uint1 x228;
  uint64_t x229;
  fiat_p_uint1 x230;
  uint64_t x231;
  uint64_t x232;
  fiat_p_uint1 x233;
  uint64_t x234;
  fiat_p_uint1 x235;
  uint64_t x236;
  fiat_p_uint1 x237;
  uint64_t x238;
  fiat_p_uint1 x239;
  uint64_t x240;
  fiat_p_uint1 x241;
  uint64_t x242;
  fiat_p_uint1 x243;
  uint64_t x244;
  uint64_t x245;
  uint64_t x246;
  uint64_t x247;
  uint64_t x248;
  uint64_t x249;
  uint64_t x250;
  uint64_t x251;
  uint64_t x252;
  uint64_t x253;
  uint64_t x254;
  uint64_t x255;
  fiat_p_uint1 x256;
  uint64_t x257;
  fiat_p_uint1 x258;
  uint64_t x259;
  fiat_p_uint1 x260;
  uint64_t x261;
  fiat_p_uint1 x262;
  uint64_t x263;
  uint64_t x264;
  fiat_p_uint1 x265;
  uint64_t x266;
  fiat_p_uint1 x267;
  uint64_t x268;
  fiat_p_uint1 x269;
  uint64_t x270;
  fiat_p_uint1 x271;
  uint64_t x272;
  fiat_p_uint1 x273;
  uint64_t x274;
  fiat_p_uint1 x275;
  uint64_t x276;
  uint64_t x277;
  uint64_t x278;
  uint64_t x279;
  uint64_t x280;
  uint64_t x281;
  uint64_t x282;
  uint64_t x283;
  uint64_t x284;
  uint64_t x285;
  uint64_t x286;
  fiat_p_uint1 x287;
  uint64_t x288;
  fiat_p_uint1 x289;
  uint64_t x290;
  fiat_p_uint1 x291;
  uint64_t x292;
  fiat_p_uint1 x293;
  uint64_t x294;
  uint64_t x295;
  fiat_p_uint1 x296;
  uint64_t x297;
  fiat_p_uint1 x298;
  uint64_t x299;
  fiat_p_uint1 x300;
  uint64_t x301;
  fiat_p_uint1 x302;
  uint64_t x303;
  fiat_p_uint1 x304;
  uint64_t x305;
  fiat_p_uint1 x306;
  uint64_t x307;
  uint64_t x308;
  fiat_p_uint1 x309;
  uint64_t x310;
  fiat_p_uint1 x311;
  uint64_t x312;
  fiat_p_uint1 x313;
  uint64_t x314;
  fiat_p_uint1 x315;
  uint64_t x316;
  fiat_p_uint1 x317;
  uint64_t x318;
  fiat_p_uint1 x319;
  uint64_t x320;
  uint64_t x321;
  uint64_t x322;
  uint64_t x323;
  uint64_t x324;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_p_mulx_u64(&x6, &x7, x5, (arg1[4]));
  fiat_p_mulx_u64(&x8, &x9, x5, (arg1[3]));
  fiat_p_mulx_u64(&x10, &x11, x5, (arg1[2]));
  fiat_p_mulx_u64(&x12, &x13, x5, (arg1[1]));
  fiat_p_mulx_u64(&x14, &x15, x5, (arg1[0]));
  fiat_p_addcarryx_u64(&x16, &x17, 0x0, x15, x12);
  fiat_p_addcarryx_u64(&x18, &x19, x17, x13, x10);
  fiat_p_addcarryx_u64(&x20, &x21, x19, x11, x8);
  fiat_p_addcarryx_u64(&x22, &x23, x21, x9, x6);
  x24 = (x23 + x7);
  fiat_p_mulx_u64(&x25, &x26, x14, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x27, &x28, x14, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x29, &x30, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x31, &x32, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x33, &x34, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x35, &x36, 0x0, x34, x31);
  fiat_p_addcarryx_u64(&x37, &x38, x36, x32, x29);
  fiat_p_addcarryx_u64(&x39, &x40, x38, x30, x27);
  fiat_p_addcarryx_u64(&x41, &x42, x40, x28, x25);
  x43 = (x42 + x26);
  fiat_p_addcarryx_u64(&x44, &x45, 0x0, x14, x33);
  fiat_p_addcarryx_u64(&x46, &x47, x45, x16, x35);
  fiat_p_addcarryx_u64(&x48, &x49, x47, x18, x37);
  fiat_p_addcarryx_u64(&x50, &x51, x49, x20, x39);
  fiat_p_addcarryx_u64(&x52, &x53, x51, x22, x41);
  fiat_p_addcarryx_u64(&x54, &x55, x53, x24, x43);
  fiat_p_mulx_u64(&x56, &x57, x1, (arg1[4]));
  fiat_p_mulx_u64(&x58, &x59, x1, (arg1[3]));
  fiat_p_mulx_u64(&x60, &x61, x1, (arg1[2]));
  fiat_p_mulx_u64(&x62, &x63, x1, (arg1[1]));
  fiat_p_mulx_u64(&x64, &x65, x1, (arg1[0]));
  fiat_p_addcarryx_u64(&x66, &x67, 0x0, x65, x62);
  fiat_p_addcarryx_u64(&x68, &x69, x67, x63, x60);
  fiat_p_addcarryx_u64(&x70, &x71, x69, x61, x58);
  fiat_p_addcarryx_u64(&x72, &x73, x71, x59, x56);
  x74 = (x73 + x57);
  fiat_p_addcarryx_u64(&x75, &x76, 0x0, x46, x64);
  fiat_p_addcarryx_u64(&x77, &x78, x76, x48, x66);
  fiat_p_addcarryx_u64(&x79, &x80, x78, x50, x68);
  fiat_p_addcarryx_u64(&x81, &x82, x80, x52, x70);
  fiat_p_addcarryx_u64(&x83, &x84, x82, x54, x72);
  fiat_p_addcarryx_u64(&x85, &x86, x84, x55, x74);
  fiat_p_mulx_u64(&x87, &x88, x75, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x89, &x90, x75, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x91, &x92, x75, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x93, &x94, x75, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x95, &x96, x75, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x97, &x98, 0x0, x96, x93);
  fiat_p_addcarryx_u64(&x99, &x100, x98, x94, x91);
  fiat_p_addcarryx_u64(&x101, &x102, x100, x92, x89);
  fiat_p_addcarryx_u64(&x103, &x104, x102, x90, x87);
  x105 = (x104 + x88);
  fiat_p_addcarryx_u64(&x106, &x107, 0x0, x75, x95);
  fiat_p_addcarryx_u64(&x108, &x109, x107, x77, x97);
  fiat_p_addcarryx_u64(&x110, &x111, x109, x79, x99);
  fiat_p_addcarryx_u64(&x112, &x113, x111, x81, x101);
  fiat_p_addcarryx_u64(&x114, &x115, x113, x83, x103);
  fiat_p_addcarryx_u64(&x116, &x117, x115, x85, x105);
  x118 = ((uint64_t)x117 + x86);
  fiat_p_mulx_u64(&x119, &x120, x2, (arg1[4]));
  fiat_p_mulx_u64(&x121, &x122, x2, (arg1[3]));
  fiat_p_mulx_u64(&x123, &x124, x2, (arg1[2]));
  fiat_p_mulx_u64(&x125, &x126, x2, (arg1[1]));
  fiat_p_mulx_u64(&x127, &x128, x2, (arg1[0]));
  fiat_p_addcarryx_u64(&x129, &x130, 0x0, x128, x125);
  fiat_p_addcarryx_u64(&x131, &x132, x130, x126, x123);
  fiat_p_addcarryx_u64(&x133, &x134, x132, x124, x121);
  fiat_p_addcarryx_u64(&x135, &x136, x134, x122, x119);
  x137 = (x136 + x120);
  fiat_p_addcarryx_u64(&x138, &x139, 0x0, x108, x127);
  fiat_p_addcarryx_u64(&x140, &x141, x139, x110, x129);
  fiat_p_addcarryx_u64(&x142, &x143, x141, x112, x131);
  fiat_p_addcarryx_u64(&x144, &x145, x143, x114, x133);
  fiat_p_addcarryx_u64(&x146, &x147, x145, x116, x135);
  fiat_p_addcarryx_u64(&x148, &x149, x147, x118, x137);
  fiat_p_mulx_u64(&x150, &x151, x138, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x152, &x153, x138, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x154, &x155, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x156, &x157, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x158, &x159, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x160, &x161, 0x0, x159, x156);
  fiat_p_addcarryx_u64(&x162, &x163, x161, x157, x154);
  fiat_p_addcarryx_u64(&x164, &x165, x163, x155, x152);
  fiat_p_addcarryx_u64(&x166, &x167, x165, x153, x150);
  x168 = (x167 + x151);
  fiat_p_addcarryx_u64(&x169, &x170, 0x0, x138, x158);
  fiat_p_addcarryx_u64(&x171, &x172, x170, x140, x160);
  fiat_p_addcarryx_u64(&x173, &x174, x172, x142, x162);
  fiat_p_addcarryx_u64(&x175, &x176, x174, x144, x164);
  fiat_p_addcarryx_u64(&x177, &x178, x176, x146, x166);
  fiat_p_addcarryx_u64(&x179, &x180, x178, x148, x168);
  x181 = ((uint64_t)x180 + x149);
  fiat_p_mulx_u64(&x182, &x183, x3, (arg1[4]));
  fiat_p_mulx_u64(&x184, &x185, x3, (arg1[3]));
  fiat_p_mulx_u64(&x186, &x187, x3, (arg1[2]));
  fiat_p_mulx_u64(&x188, &x189, x3, (arg1[1]));
  fiat_p_mulx_u64(&x190, &x191, x3, (arg1[0]));
  fiat_p_addcarryx_u64(&x192, &x193, 0x0, x191, x188);
  fiat_p_addcarryx_u64(&x194, &x195, x193, x189, x186);
  fiat_p_addcarryx_u64(&x196, &x197, x195, x187, x184);
  fiat_p_addcarryx_u64(&x198, &x199, x197, x185, x182);
  x200 = (x199 + x183);
  fiat_p_addcarryx_u64(&x201, &x202, 0x0, x171, x190);
  fiat_p_addcarryx_u64(&x203, &x204, x202, x173, x192);
  fiat_p_addcarryx_u64(&x205, &x206, x204, x175, x194);
  fiat_p_addcarryx_u64(&x207, &x208, x206, x177, x196);
  fiat_p_addcarryx_u64(&x209, &x210, x208, x179, x198);
  fiat_p_addcarryx_u64(&x211, &x212, x210, x181, x200);
  fiat_p_mulx_u64(&x213, &x214, x201, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x215, &x216, x201, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x217, &x218, x201, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x219, &x220, x201, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x221, &x222, x201, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x223, &x224, 0x0, x222, x219);
  fiat_p_addcarryx_u64(&x225, &x226, x224, x220, x217);
  fiat_p_addcarryx_u64(&x227, &x228, x226, x218, x215);
  fiat_p_addcarryx_u64(&x229, &x230, x228, x216, x213);
  x231 = (x230 + x214);
  fiat_p_addcarryx_u64(&x232, &x233, 0x0, x201, x221);
  fiat_p_addcarryx_u64(&x234, &x235, x233, x203, x223);
  fiat_p_addcarryx_u64(&x236, &x237, x235, x205, x225);
  fiat_p_addcarryx_u64(&x238, &x239, x237, x207, x227);
  fiat_p_addcarryx_u64(&x240, &x241, x239, x209, x229);
  fiat_p_addcarryx_u64(&x242, &x243, x241, x211, x231);
  x244 = ((uint64_t)x243 + x212);
  fiat_p_mulx_u64(&x245, &x246, x4, (arg1[4]));
  fiat_p_mulx_u64(&x247, &x248, x4, (arg1[3]));
  fiat_p_mulx_u64(&x249, &x250, x4, (arg1[2]));
  fiat_p_mulx_u64(&x251, &x252, x4, (arg1[1]));
  fiat_p_mulx_u64(&x253, &x254, x4, (arg1[0]));
  fiat_p_addcarryx_u64(&x255, &x256, 0x0, x254, x251);
  fiat_p_addcarryx_u64(&x257, &x258, x256, x252, x249);
  fiat_p_addcarryx_u64(&x259, &x260, x258, x250, x247);
  fiat_p_addcarryx_u64(&x261, &x262, x260, x248, x245);
  x263 = (x262 + x246);
  fiat_p_addcarryx_u64(&x264, &x265, 0x0, x234, x253);
  fiat_p_addcarryx_u64(&x266, &x267, x265, x236, x255);
  fiat_p_addcarryx_u64(&x268, &x269, x267, x238, x257);
  fiat_p_addcarryx_u64(&x270, &x271, x269, x240, x259);
  fiat_p_addcarryx_u64(&x272, &x273, x271, x242, x261);
  fiat_p_addcarryx_u64(&x274, &x275, x273, x244, x263);
  fiat_p_mulx_u64(&x276, &x277, x264, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x278, &x279, x264, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x280, &x281, x264, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x282, &x283, x264, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x284, &x285, x264, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x286, &x287, 0x0, x285, x282);
  fiat_p_addcarryx_u64(&x288, &x289, x287, x283, x280);
  fiat_p_addcarryx_u64(&x290, &x291, x289, x281, x278);
  fiat_p_addcarryx_u64(&x292, &x293, x291, x279, x276);
  x294 = (x293 + x277);
  fiat_p_addcarryx_u64(&x295, &x296, 0x0, x264, x284);
  fiat_p_addcarryx_u64(&x297, &x298, x296, x266, x286);
  fiat_p_addcarryx_u64(&x299, &x300, x298, x268, x288);
  fiat_p_addcarryx_u64(&x301, &x302, x300, x270, x290);
  fiat_p_addcarryx_u64(&x303, &x304, x302, x272, x292);
  fiat_p_addcarryx_u64(&x305, &x306, x304, x274, x294);
  x307 = ((uint64_t)x306 + x275);
  fiat_p_subborrowx_u64(&x308, &x309, 0x0, x297, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x310, &x311, x309, x299, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x312, &x313, x311, x301, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x314, &x315, x313, x303, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x316, &x317, x315, x305, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x318, &x319, x317, x307, 0x0);
  fiat_p_cmovznz_u64(&x320, x319, x308, x297);
  fiat_p_cmovznz_u64(&x321, x319, x310, x299);
  fiat_p_cmovznz_u64(&x322, x319, x312, x301);
  fiat_p_cmovznz_u64(&x323, x319, x314, x303);
  fiat_p_cmovznz_u64(&x324, x319, x316, x305);
  out1[0] = x320;
  out1[1] = x321;
  out1[2] = x322;
  out1[3] = x323;
  out1[4] = x324;
}

/*
 * The function fiat_p_add adds two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) + eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_add(fiat_p_montgomery_domain_field_element out1, const fiat_p_montgomery_domain_field_element arg1, const fiat_p_montgomery_domain_field_element arg2) {
  uint64_t x1;
  fiat_p_uint1 x2;
  uint64_t x3;
  fiat_p_uint1 x4;
  uint64_t x5;
  fiat_p_uint1 x6;
  uint64_t x7;
  fiat_p_uint1 x8;
  uint64_t x9;
  fiat_p_uint1 x10;
  uint64_t x11;
  fiat_p_uint1 x12;
  uint64_t x13;
  fiat_p_uint1 x14;
  uint64_t x15;
  fiat_p_uint1 x16;
  uint64_t x17;
  fiat_p_uint1 x18;
  uint64_t x19;
  fiat_p_uint1 x20;
  uint64_t x21;
  fiat_p_uint1 x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  fiat_p_addcarryx_u64(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_p_addcarryx_u64(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_p_addcarryx_u64(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_p_addcarryx_u64(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_p_addcarryx_u64(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_p_subborrowx_u64(&x11, &x12, 0x0, x1, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x13, &x14, x12, x3, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x15, &x16, x14, x5, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x17, &x18, x16, x7, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x19, &x20, x18, x9, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x21, &x22, x20, x10, 0x0);
  fiat_p_cmovznz_u64(&x23, x22, x11, x1);
  fiat_p_cmovznz_u64(&x24, x22, x13, x3);
  fiat_p_cmovznz_u64(&x25, x22, x15, x5);
  fiat_p_cmovznz_u64(&x26, x22, x17, x7);
  fiat_p_cmovznz_u64(&x27, x22, x19, x9);
  out1[0] = x23;
  out1[1] = x24;
  out1[2] = x25;
  out1[3] = x26;
  out1[4] = x27;
}

/*
 * The function fiat_p_sub subtracts two field elements in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 *   0 ≤ eval arg2 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) - eval (from_montgomery arg2)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_sub(fiat_p_montgomery_domain_field_element out1, const fiat_p_montgomery_domain_field_element arg1, const fiat_p_montgomery_domain_field_element arg2) {
  uint64_t x1;
  fiat_p_uint1 x2;
  uint64_t x3;
  fiat_p_uint1 x4;
  uint64_t x5;
  fiat_p_uint1 x6;
  uint64_t x7;
  fiat_p_uint1 x8;
  uint64_t x9;
  fiat_p_uint1 x10;
  uint64_t x11;
  uint64_t x12;
  fiat_p_uint1 x13;
  uint64_t x14;
  fiat_p_uint1 x15;
  uint64_t x16;
  fiat_p_uint1 x17;
  uint64_t x18;
  fiat_p_uint1 x19;
  uint64_t x20;
  fiat_p_uint1 x21;
  fiat_p_subborrowx_u64(&x1, &x2, 0x0, (arg1[0]), (arg2[0]));
  fiat_p_subborrowx_u64(&x3, &x4, x2, (arg1[1]), (arg2[1]));
  fiat_p_subborrowx_u64(&x5, &x6, x4, (arg1[2]), (arg2[2]));
  fiat_p_subborrowx_u64(&x7, &x8, x6, (arg1[3]), (arg2[3]));
  fiat_p_subborrowx_u64(&x9, &x10, x8, (arg1[4]), (arg2[4]));
  fiat_p_cmovznz_u64(&x11, x10, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x12, &x13, 0x0, x1, x11);
  fiat_p_addcarryx_u64(&x14, &x15, x13, x3, x11);
  fiat_p_addcarryx_u64(&x16, &x17, x15, x5, x11);
  fiat_p_addcarryx_u64(&x18, &x19, x17, x7, (x11 & UINT64_C(0xe2639b854da79fe3)));
  fiat_p_addcarryx_u64(&x20, &x21, x19, x9, (x11 & UINT64_C(0x1ae2e77fe01)));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_p_opp negates a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = -eval (from_montgomery arg1) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_opp(fiat_p_montgomery_domain_field_element out1, const fiat_p_montgomery_domain_field_element arg1) {
  uint64_t x1;
  fiat_p_uint1 x2;
  uint64_t x3;
  fiat_p_uint1 x4;
  uint64_t x5;
  fiat_p_uint1 x6;
  uint64_t x7;
  fiat_p_uint1 x8;
  uint64_t x9;
  fiat_p_uint1 x10;
  uint64_t x11;
  uint64_t x12;
  fiat_p_uint1 x13;
  uint64_t x14;
  fiat_p_uint1 x15;
  uint64_t x16;
  fiat_p_uint1 x17;
  uint64_t x18;
  fiat_p_uint1 x19;
  uint64_t x20;
  fiat_p_uint1 x21;
  fiat_p_subborrowx_u64(&x1, &x2, 0x0, 0x0, (arg1[0]));
  fiat_p_subborrowx_u64(&x3, &x4, x2, 0x0, (arg1[1]));
  fiat_p_subborrowx_u64(&x5, &x6, x4, 0x0, (arg1[2]));
  fiat_p_subborrowx_u64(&x7, &x8, x6, 0x0, (arg1[3]));
  fiat_p_subborrowx_u64(&x9, &x10, x8, 0x0, (arg1[4]));
  fiat_p_cmovznz_u64(&x11, x10, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x12, &x13, 0x0, x1, x11);
  fiat_p_addcarryx_u64(&x14, &x15, x13, x3, x11);
  fiat_p_addcarryx_u64(&x16, &x17, x15, x5, x11);
  fiat_p_addcarryx_u64(&x18, &x19, x17, x7, (x11 & UINT64_C(0xe2639b854da79fe3)));
  fiat_p_addcarryx_u64(&x20, &x21, x19, x9, (x11 & UINT64_C(0x1ae2e77fe01)));
  out1[0] = x12;
  out1[1] = x14;
  out1[2] = x16;
  out1[3] = x18;
  out1[4] = x20;
}

/*
 * The function fiat_p_from_montgomery translates a field element out of the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * ((2^64)⁻¹ mod m)^5) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_from_montgomery(fiat_p_non_montgomery_domain_field_element out1, const fiat_p_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  fiat_p_uint1 x13;
  uint64_t x14;
  fiat_p_uint1 x15;
  uint64_t x16;
  fiat_p_uint1 x17;
  uint64_t x18;
  fiat_p_uint1 x19;
  uint64_t x20;
  fiat_p_uint1 x21;
  uint64_t x22;
  fiat_p_uint1 x23;
  uint64_t x24;
  fiat_p_uint1 x25;
  uint64_t x26;
  fiat_p_uint1 x27;
  uint64_t x28;
  fiat_p_uint1 x29;
  uint64_t x30;
  fiat_p_uint1 x31;
  uint64_t x32;
  fiat_p_uint1 x33;
  uint64_t x34;
  fiat_p_uint1 x35;
  uint64_t x36;
  fiat_p_uint1 x37;
  uint64_t x38;
  uint64_t x39;
  uint64_t x40;
  uint64_t x41;
  uint64_t x42;
  uint64_t x43;
  uint64_t x44;
  uint64_t x45;
  uint64_t x46;
  uint64_t x47;
  uint64_t x48;
  fiat_p_uint1 x49;
  uint64_t x50;
  fiat_p_uint1 x51;
  uint64_t x52;
  fiat_p_uint1 x53;
  uint64_t x54;
  fiat_p_uint1 x55;
  uint64_t x56;
  fiat_p_uint1 x57;
  uint64_t x58;
  fiat_p_uint1 x59;
  uint64_t x60;
  fiat_p_uint1 x61;
  uint64_t x62;
  fiat_p_uint1 x63;
  uint64_t x64;
  fiat_p_uint1 x65;
  uint64_t x66;
  fiat_p_uint1 x67;
  uint64_t x68;
  fiat_p_uint1 x69;
  uint64_t x70;
  fiat_p_uint1 x71;
  uint64_t x72;
  fiat_p_uint1 x73;
  uint64_t x74;
  uint64_t x75;
  uint64_t x76;
  uint64_t x77;
  uint64_t x78;
  uint64_t x79;
  uint64_t x80;
  uint64_t x81;
  uint64_t x82;
  uint64_t x83;
  uint64_t x84;
  fiat_p_uint1 x85;
  uint64_t x86;
  fiat_p_uint1 x87;
  uint64_t x88;
  fiat_p_uint1 x89;
  uint64_t x90;
  fiat_p_uint1 x91;
  uint64_t x92;
  fiat_p_uint1 x93;
  uint64_t x94;
  fiat_p_uint1 x95;
  uint64_t x96;
  fiat_p_uint1 x97;
  uint64_t x98;
  fiat_p_uint1 x99;
  uint64_t x100;
  fiat_p_uint1 x101;
  uint64_t x102;
  fiat_p_uint1 x103;
  uint64_t x104;
  fiat_p_uint1 x105;
  uint64_t x106;
  fiat_p_uint1 x107;
  uint64_t x108;
  fiat_p_uint1 x109;
  uint64_t x110;
  uint64_t x111;
  uint64_t x112;
  uint64_t x113;
  uint64_t x114;
  uint64_t x115;
  uint64_t x116;
  uint64_t x117;
  uint64_t x118;
  uint64_t x119;
  uint64_t x120;
  fiat_p_uint1 x121;
  uint64_t x122;
  fiat_p_uint1 x123;
  uint64_t x124;
  fiat_p_uint1 x125;
  uint64_t x126;
  fiat_p_uint1 x127;
  uint64_t x128;
  fiat_p_uint1 x129;
  uint64_t x130;
  fiat_p_uint1 x131;
  uint64_t x132;
  fiat_p_uint1 x133;
  uint64_t x134;
  fiat_p_uint1 x135;
  uint64_t x136;
  fiat_p_uint1 x137;
  uint64_t x138;
  fiat_p_uint1 x139;
  uint64_t x140;
  fiat_p_uint1 x141;
  uint64_t x142;
  fiat_p_uint1 x143;
  uint64_t x144;
  fiat_p_uint1 x145;
  uint64_t x146;
  uint64_t x147;
  uint64_t x148;
  uint64_t x149;
  uint64_t x150;
  uint64_t x151;
  uint64_t x152;
  uint64_t x153;
  uint64_t x154;
  uint64_t x155;
  uint64_t x156;
  fiat_p_uint1 x157;
  uint64_t x158;
  fiat_p_uint1 x159;
  uint64_t x160;
  fiat_p_uint1 x161;
  uint64_t x162;
  fiat_p_uint1 x163;
  uint64_t x164;
  fiat_p_uint1 x165;
  uint64_t x166;
  fiat_p_uint1 x167;
  uint64_t x168;
  fiat_p_uint1 x169;
  uint64_t x170;
  fiat_p_uint1 x171;
  uint64_t x172;
  fiat_p_uint1 x173;
  uint64_t x174;
  uint64_t x175;
  fiat_p_uint1 x176;
  uint64_t x177;
  fiat_p_uint1 x178;
  uint64_t x179;
  fiat_p_uint1 x180;
  uint64_t x181;
  fiat_p_uint1 x182;
  uint64_t x183;
  fiat_p_uint1 x184;
  uint64_t x185;
  fiat_p_uint1 x186;
  uint64_t x187;
  uint64_t x188;
  uint64_t x189;
  uint64_t x190;
  uint64_t x191;
  x1 = (arg1[0]);
  fiat_p_mulx_u64(&x2, &x3, x1, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x4, &x5, x1, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x6, &x7, x1, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x8, &x9, x1, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x10, &x11, x1, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x12, &x13, 0x0, x11, x8);
  fiat_p_addcarryx_u64(&x14, &x15, x13, x9, x6);
  fiat_p_addcarryx_u64(&x16, &x17, x15, x7, x4);
  fiat_p_addcarryx_u64(&x18, &x19, x17, x5, x2);
  fiat_p_addcarryx_u64(&x20, &x21, 0x0, x1, x10);
  fiat_p_addcarryx_u64(&x22, &x23, x21, 0x0, x12);
  fiat_p_addcarryx_u64(&x24, &x25, x23, 0x0, x14);
  fiat_p_addcarryx_u64(&x26, &x27, x25, 0x0, x16);
  fiat_p_addcarryx_u64(&x28, &x29, x27, 0x0, x18);
  fiat_p_addcarryx_u64(&x30, &x31, 0x0, x22, (arg1[1]));
  fiat_p_addcarryx_u64(&x32, &x33, x31, x24, 0x0);
  fiat_p_addcarryx_u64(&x34, &x35, x33, x26, 0x0);
  fiat_p_addcarryx_u64(&x36, &x37, x35, x28, 0x0);
  fiat_p_mulx_u64(&x38, &x39, x30, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x40, &x41, x30, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x42, &x43, x30, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x44, &x45, x30, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x46, &x47, x30, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x48, &x49, 0x0, x47, x44);
  fiat_p_addcarryx_u64(&x50, &x51, x49, x45, x42);
  fiat_p_addcarryx_u64(&x52, &x53, x51, x43, x40);
  fiat_p_addcarryx_u64(&x54, &x55, x53, x41, x38);
  fiat_p_addcarryx_u64(&x56, &x57, 0x0, x30, x46);
  fiat_p_addcarryx_u64(&x58, &x59, x57, x32, x48);
  fiat_p_addcarryx_u64(&x60, &x61, x59, x34, x50);
  fiat_p_addcarryx_u64(&x62, &x63, x61, x36, x52);
  fiat_p_addcarryx_u64(&x64, &x65, x63, (x37 + (x29 + (x19 + x3))), x54);
  fiat_p_addcarryx_u64(&x66, &x67, 0x0, x58, (arg1[2]));
  fiat_p_addcarryx_u64(&x68, &x69, x67, x60, 0x0);
  fiat_p_addcarryx_u64(&x70, &x71, x69, x62, 0x0);
  fiat_p_addcarryx_u64(&x72, &x73, x71, x64, 0x0);
  fiat_p_mulx_u64(&x74, &x75, x66, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x76, &x77, x66, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x78, &x79, x66, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x80, &x81, x66, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x82, &x83, x66, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x84, &x85, 0x0, x83, x80);
  fiat_p_addcarryx_u64(&x86, &x87, x85, x81, x78);
  fiat_p_addcarryx_u64(&x88, &x89, x87, x79, x76);
  fiat_p_addcarryx_u64(&x90, &x91, x89, x77, x74);
  fiat_p_addcarryx_u64(&x92, &x93, 0x0, x66, x82);
  fiat_p_addcarryx_u64(&x94, &x95, x93, x68, x84);
  fiat_p_addcarryx_u64(&x96, &x97, x95, x70, x86);
  fiat_p_addcarryx_u64(&x98, &x99, x97, x72, x88);
  fiat_p_addcarryx_u64(&x100, &x101, x99, (x73 + (x65 + (x55 + x39))), x90);
  fiat_p_addcarryx_u64(&x102, &x103, 0x0, x94, (arg1[3]));
  fiat_p_addcarryx_u64(&x104, &x105, x103, x96, 0x0);
  fiat_p_addcarryx_u64(&x106, &x107, x105, x98, 0x0);
  fiat_p_addcarryx_u64(&x108, &x109, x107, x100, 0x0);
  fiat_p_mulx_u64(&x110, &x111, x102, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x112, &x113, x102, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x114, &x115, x102, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x116, &x117, x102, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x118, &x119, x102, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x120, &x121, 0x0, x119, x116);
  fiat_p_addcarryx_u64(&x122, &x123, x121, x117, x114);
  fiat_p_addcarryx_u64(&x124, &x125, x123, x115, x112);
  fiat_p_addcarryx_u64(&x126, &x127, x125, x113, x110);
  fiat_p_addcarryx_u64(&x128, &x129, 0x0, x102, x118);
  fiat_p_addcarryx_u64(&x130, &x131, x129, x104, x120);
  fiat_p_addcarryx_u64(&x132, &x133, x131, x106, x122);
  fiat_p_addcarryx_u64(&x134, &x135, x133, x108, x124);
  fiat_p_addcarryx_u64(&x136, &x137, x135, (x109 + (x101 + (x91 + x75))), x126);
  fiat_p_addcarryx_u64(&x138, &x139, 0x0, x130, (arg1[4]));
  fiat_p_addcarryx_u64(&x140, &x141, x139, x132, 0x0);
  fiat_p_addcarryx_u64(&x142, &x143, x141, x134, 0x0);
  fiat_p_addcarryx_u64(&x144, &x145, x143, x136, 0x0);
  fiat_p_mulx_u64(&x146, &x147, x138, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x148, &x149, x138, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x150, &x151, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x152, &x153, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x154, &x155, x138, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x156, &x157, 0x0, x155, x152);
  fiat_p_addcarryx_u64(&x158, &x159, x157, x153, x150);
  fiat_p_addcarryx_u64(&x160, &x161, x159, x151, x148);
  fiat_p_addcarryx_u64(&x162, &x163, x161, x149, x146);
  fiat_p_addcarryx_u64(&x164, &x165, 0x0, x138, x154);
  fiat_p_addcarryx_u64(&x166, &x167, x165, x140, x156);
  fiat_p_addcarryx_u64(&x168, &x169, x167, x142, x158);
  fiat_p_addcarryx_u64(&x170, &x171, x169, x144, x160);
  fiat_p_addcarryx_u64(&x172, &x173, x171, (x145 + (x137 + (x127 + x111))), x162);
  x174 = (x173 + (x163 + x147));
  fiat_p_subborrowx_u64(&x175, &x176, 0x0, x166, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x177, &x178, x176, x168, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x179, &x180, x178, x170, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x181, &x182, x180, x172, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x183, &x184, x182, x174, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x185, &x186, x184, 0x0, 0x0);
  fiat_p_cmovznz_u64(&x187, x186, x175, x166);
  fiat_p_cmovznz_u64(&x188, x186, x177, x168);
  fiat_p_cmovznz_u64(&x189, x186, x179, x170);
  fiat_p_cmovznz_u64(&x190, x186, x181, x172);
  fiat_p_cmovznz_u64(&x191, x186, x183, x174);
  out1[0] = x187;
  out1[1] = x188;
  out1[2] = x189;
  out1[3] = x190;
  out1[4] = x191;
}

/*
 * The function fiat_p_to_montgomery translates a field element into the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_to_montgomery(fiat_p_montgomery_domain_field_element out1, const fiat_p_non_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  fiat_p_uint1 x17;
  uint64_t x18;
  fiat_p_uint1 x19;
  uint64_t x20;
  fiat_p_uint1 x21;
  uint64_t x22;
  fiat_p_uint1 x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  uint64_t x32;
  uint64_t x33;
  uint64_t x34;
  fiat_p_uint1 x35;
  uint64_t x36;
  fiat_p_uint1 x37;
  uint64_t x38;
  fiat_p_uint1 x39;
  uint64_t x40;
  fiat_p_uint1 x41;
  uint64_t x42;
  fiat_p_uint1 x43;
  uint64_t x44;
  fiat_p_uint1 x45;
  uint64_t x46;
  fiat_p_uint1 x47;
  uint64_t x48;
  fiat_p_uint1 x49;
  uint64_t x50;
  fiat_p_uint1 x51;
  uint64_t x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  fiat_p_uint1 x63;
  uint64_t x64;
  fiat_p_uint1 x65;
  uint64_t x66;
  fiat_p_uint1 x67;
  uint64_t x68;
  fiat_p_uint1 x69;
  uint64_t x70;
  fiat_p_uint1 x71;
  uint64_t x72;
  fiat_p_uint1 x73;
  uint64_t x74;
  fiat_p_uint1 x75;
  uint64_t x76;
  fiat_p_uint1 x77;
  uint64_t x78;
  fiat_p_uint1 x79;
  uint64_t x80;
  uint64_t x81;
  uint64_t x82;
  uint64_t x83;
  uint64_t x84;
  uint64_t x85;
  uint64_t x86;
  uint64_t x87;
  uint64_t x88;
  uint64_t x89;
  uint64_t x90;
  fiat_p_uint1 x91;
  uint64_t x92;
  fiat_p_uint1 x93;
  uint64_t x94;
  fiat_p_uint1 x95;
  uint64_t x96;
  fiat_p_uint1 x97;
  uint64_t x98;
  fiat_p_uint1 x99;
  uint64_t x100;
  fiat_p_uint1 x101;
  uint64_t x102;
  fiat_p_uint1 x103;
  uint64_t x104;
  fiat_p_uint1 x105;
  uint64_t x106;
  fiat_p_uint1 x107;
  uint64_t x108;
  uint64_t x109;
  uint64_t x110;
  uint64_t x111;
  uint64_t x112;
  uint64_t x113;
  uint64_t x114;
  uint64_t x115;
  uint64_t x116;
  uint64_t x117;
  uint64_t x118;
  fiat_p_uint1 x119;
  uint64_t x120;
  fiat_p_uint1 x121;
  uint64_t x122;
  fiat_p_uint1 x123;
  uint64_t x124;
  fiat_p_uint1 x125;
  uint64_t x126;
  fiat_p_uint1 x127;
  uint64_t x128;
  fiat_p_uint1 x129;
  uint64_t x130;
  fiat_p_uint1 x131;
  uint64_t x132;
  fiat_p_uint1 x133;
  uint64_t x134;
  fiat_p_uint1 x135;
  uint64_t x136;
  uint64_t x137;
  uint64_t x138;
  uint64_t x139;
  uint64_t x140;
  uint64_t x141;
  uint64_t x142;
  uint64_t x143;
  uint64_t x144;
  uint64_t x145;
  uint64_t x146;
  fiat_p_uint1 x147;
  uint64_t x148;
  fiat_p_uint1 x149;
  uint64_t x150;
  fiat_p_uint1 x151;
  uint64_t x152;
  fiat_p_uint1 x153;
  uint64_t x154;
  fiat_p_uint1 x155;
  uint64_t x156;
  fiat_p_uint1 x157;
  uint64_t x158;
  fiat_p_uint1 x159;
  uint64_t x160;
  fiat_p_uint1 x161;
  uint64_t x162;
  fiat_p_uint1 x163;
  uint64_t x164;
  uint64_t x165;
  uint64_t x166;
  uint64_t x167;
  uint64_t x168;
  uint64_t x169;
  uint64_t x170;
  uint64_t x171;
  uint64_t x172;
  uint64_t x173;
  uint64_t x174;
  fiat_p_uint1 x175;
  uint64_t x176;
  fiat_p_uint1 x177;
  uint64_t x178;
  fiat_p_uint1 x179;
  uint64_t x180;
  fiat_p_uint1 x181;
  uint64_t x182;
  fiat_p_uint1 x183;
  uint64_t x184;
  fiat_p_uint1 x185;
  uint64_t x186;
  fiat_p_uint1 x187;
  uint64_t x188;
  fiat_p_uint1 x189;
  uint64_t x190;
  fiat_p_uint1 x191;
  uint64_t x192;
  uint64_t x193;
  uint64_t x194;
  uint64_t x195;
  uint64_t x196;
  uint64_t x197;
  uint64_t x198;
  uint64_t x199;
  uint64_t x200;
  uint64_t x201;
  uint64_t x202;
  fiat_p_uint1 x203;
  uint64_t x204;
  fiat_p_uint1 x205;
  uint64_t x206;
  fiat_p_uint1 x207;
  uint64_t x208;
  fiat_p_uint1 x209;
  uint64_t x210;
  fiat_p_uint1 x211;
  uint64_t x212;
  fiat_p_uint1 x213;
  uint64_t x214;
  fiat_p_uint1 x215;
  uint64_t x216;
  fiat_p_uint1 x217;
  uint64_t x218;
  fiat_p_uint1 x219;
  uint64_t x220;
  uint64_t x221;
  uint64_t x222;
  uint64_t x223;
  uint64_t x224;
  uint64_t x225;
  uint64_t x226;
  uint64_t x227;
  uint64_t x228;
  uint64_t x229;
  uint64_t x230;
  fiat_p_uint1 x231;
  uint64_t x232;
  fiat_p_uint1 x233;
  uint64_t x234;
  fiat_p_uint1 x235;
  uint64_t x236;
  fiat_p_uint1 x237;
  uint64_t x238;
  fiat_p_uint1 x239;
  uint64_t x240;
  fiat_p_uint1 x241;
  uint64_t x242;
  fiat_p_uint1 x243;
  uint64_t x244;
  fiat_p_uint1 x245;
  uint64_t x246;
  fiat_p_uint1 x247;
  uint64_t x248;
  uint64_t x249;
  uint64_t x250;
  uint64_t x251;
  uint64_t x252;
  uint64_t x253;
  uint64_t x254;
  uint64_t x255;
  uint64_t x256;
  uint64_t x257;
  uint64_t x258;
  fiat_p_uint1 x259;
  uint64_t x260;
  fiat_p_uint1 x261;
  uint64_t x262;
  fiat_p_uint1 x263;
  uint64_t x264;
  fiat_p_uint1 x265;
  uint64_t x266;
  fiat_p_uint1 x267;
  uint64_t x268;
  fiat_p_uint1 x269;
  uint64_t x270;
  fiat_p_uint1 x271;
  uint64_t x272;
  fiat_p_uint1 x273;
  uint64_t x274;
  fiat_p_uint1 x275;
  uint64_t x276;
  uint64_t x277;
  fiat_p_uint1 x278;
  uint64_t x279;
  fiat_p_uint1 x280;
  uint64_t x281;
  fiat_p_uint1 x282;
  uint64_t x283;
  fiat_p_uint1 x284;
  uint64_t x285;
  fiat_p_uint1 x286;
  uint64_t x287;
  fiat_p_uint1 x288;
  uint64_t x289;
  uint64_t x290;
  uint64_t x291;
  uint64_t x292;
  uint64_t x293;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[4]);
  x5 = (arg1[0]);
  fiat_p_mulx_u64(&x6, &x7, x5, UINT64_C(0x16e25bb319));
  fiat_p_mulx_u64(&x8, &x9, x5, UINT64_C(0xc4090ace285ae4b));
  fiat_p_mulx_u64(&x10, &x11, x5, UINT64_C(0x436d462f60fe53fc));
  fiat_p_mulx_u64(&x12, &x13, x5, UINT64_C(0x3cccfaf93709ad2f));
  fiat_p_mulx_u64(&x14, &x15, x5, UINT64_C(0x54c8f86fdde71429));
  fiat_p_addcarryx_u64(&x16, &x17, 0x0, x15, x12);
  fiat_p_addcarryx_u64(&x18, &x19, x17, x13, x10);
  fiat_p_addcarryx_u64(&x20, &x21, x19, x11, x8);
  fiat_p_addcarryx_u64(&x22, &x23, x21, x9, x6);
  fiat_p_mulx_u64(&x24, &x25, x14, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x26, &x27, x14, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x28, &x29, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x30, &x31, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x32, &x33, x14, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x34, &x35, 0x0, x33, x30);
  fiat_p_addcarryx_u64(&x36, &x37, x35, x31, x28);
  fiat_p_addcarryx_u64(&x38, &x39, x37, x29, x26);
  fiat_p_addcarryx_u64(&x40, &x41, x39, x27, x24);
  fiat_p_addcarryx_u64(&x42, &x43, 0x0, x14, x32);
  fiat_p_addcarryx_u64(&x44, &x45, x43, x16, x34);
  fiat_p_addcarryx_u64(&x46, &x47, x45, x18, x36);
  fiat_p_addcarryx_u64(&x48, &x49, x47, x20, x38);
  fiat_p_addcarryx_u64(&x50, &x51, x49, x22, x40);
  fiat_p_mulx_u64(&x52, &x53, x1, UINT64_C(0x16e25bb319));
  fiat_p_mulx_u64(&x54, &x55, x1, UINT64_C(0xc4090ace285ae4b));
  fiat_p_mulx_u64(&x56, &x57, x1, UINT64_C(0x436d462f60fe53fc));
  fiat_p_mulx_u64(&x58, &x59, x1, UINT64_C(0x3cccfaf93709ad2f));
  fiat_p_mulx_u64(&x60, &x61, x1, UINT64_C(0x54c8f86fdde71429));
  fiat_p_addcarryx_u64(&x62, &x63, 0x0, x61, x58);
  fiat_p_addcarryx_u64(&x64, &x65, x63, x59, x56);
  fiat_p_addcarryx_u64(&x66, &x67, x65, x57, x54);
  fiat_p_addcarryx_u64(&x68, &x69, x67, x55, x52);
  fiat_p_addcarryx_u64(&x70, &x71, 0x0, x44, x60);
  fiat_p_addcarryx_u64(&x72, &x73, x71, x46, x62);
  fiat_p_addcarryx_u64(&x74, &x75, x73, x48, x64);
  fiat_p_addcarryx_u64(&x76, &x77, x75, x50, x66);
  fiat_p_addcarryx_u64(&x78, &x79, x77, ((x51 + (x23 + x7)) + (x41 + x25)), x68);
  fiat_p_mulx_u64(&x80, &x81, x70, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x82, &x83, x70, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x84, &x85, x70, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x86, &x87, x70, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x88, &x89, x70, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x90, &x91, 0x0, x89, x86);
  fiat_p_addcarryx_u64(&x92, &x93, x91, x87, x84);
  fiat_p_addcarryx_u64(&x94, &x95, x93, x85, x82);
  fiat_p_addcarryx_u64(&x96, &x97, x95, x83, x80);
  fiat_p_addcarryx_u64(&x98, &x99, 0x0, x70, x88);
  fiat_p_addcarryx_u64(&x100, &x101, x99, x72, x90);
  fiat_p_addcarryx_u64(&x102, &x103, x101, x74, x92);
  fiat_p_addcarryx_u64(&x104, &x105, x103, x76, x94);
  fiat_p_addcarryx_u64(&x106, &x107, x105, x78, x96);
  fiat_p_mulx_u64(&x108, &x109, x2, UINT64_C(0x16e25bb319));
  fiat_p_mulx_u64(&x110, &x111, x2, UINT64_C(0xc4090ace285ae4b));
  fiat_p_mulx_u64(&x112, &x113, x2, UINT64_C(0x436d462f60fe53fc));
  fiat_p_mulx_u64(&x114, &x115, x2, UINT64_C(0x3cccfaf93709ad2f));
  fiat_p_mulx_u64(&x116, &x117, x2, UINT64_C(0x54c8f86fdde71429));
  fiat_p_addcarryx_u64(&x118, &x119, 0x0, x117, x114);
  fiat_p_addcarryx_u64(&x120, &x121, x119, x115, x112);
  fiat_p_addcarryx_u64(&x122, &x123, x121, x113, x110);
  fiat_p_addcarryx_u64(&x124, &x125, x123, x111, x108);
  fiat_p_addcarryx_u64(&x126, &x127, 0x0, x100, x116);
  fiat_p_addcarryx_u64(&x128, &x129, x127, x102, x118);
  fiat_p_addcarryx_u64(&x130, &x131, x129, x104, x120);
  fiat_p_addcarryx_u64(&x132, &x133, x131, x106, x122);
  fiat_p_addcarryx_u64(&x134, &x135, x133, ((x107 + (x79 + (x69 + x53))) + (x97 + x81)), x124);
  fiat_p_mulx_u64(&x136, &x137, x126, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x138, &x139, x126, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x140, &x141, x126, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x142, &x143, x126, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x144, &x145, x126, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x146, &x147, 0x0, x145, x142);
  fiat_p_addcarryx_u64(&x148, &x149, x147, x143, x140);
  fiat_p_addcarryx_u64(&x150, &x151, x149, x141, x138);
  fiat_p_addcarryx_u64(&x152, &x153, x151, x139, x136);
  fiat_p_addcarryx_u64(&x154, &x155, 0x0, x126, x144);
  fiat_p_addcarryx_u64(&x156, &x157, x155, x128, x146);
  fiat_p_addcarryx_u64(&x158, &x159, x157, x130, x148);
  fiat_p_addcarryx_u64(&x160, &x161, x159, x132, x150);
  fiat_p_addcarryx_u64(&x162, &x163, x161, x134, x152);
  fiat_p_mulx_u64(&x164, &x165, x3, UINT64_C(0x16e25bb319));
  fiat_p_mulx_u64(&x166, &x167, x3, UINT64_C(0xc4090ace285ae4b));
  fiat_p_mulx_u64(&x168, &x169, x3, UINT64_C(0x436d462f60fe53fc));
  fiat_p_mulx_u64(&x170, &x171, x3, UINT64_C(0x3cccfaf93709ad2f));
  fiat_p_mulx_u64(&x172, &x173, x3, UINT64_C(0x54c8f86fdde71429));
  fiat_p_addcarryx_u64(&x174, &x175, 0x0, x173, x170);
  fiat_p_addcarryx_u64(&x176, &x177, x175, x171, x168);
  fiat_p_addcarryx_u64(&x178, &x179, x177, x169, x166);
  fiat_p_addcarryx_u64(&x180, &x181, x179, x167, x164);
  fiat_p_addcarryx_u64(&x182, &x183, 0x0, x156, x172);
  fiat_p_addcarryx_u64(&x184, &x185, x183, x158, x174);
  fiat_p_addcarryx_u64(&x186, &x187, x185, x160, x176);
  fiat_p_addcarryx_u64(&x188, &x189, x187, x162, x178);
  fiat_p_addcarryx_u64(&x190, &x191, x189, ((x163 + (x135 + (x125 + x109))) + (x153 + x137)), x180);
  fiat_p_mulx_u64(&x192, &x193, x182, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x194, &x195, x182, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x196, &x197, x182, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x198, &x199, x182, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x200, &x201, x182, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x202, &x203, 0x0, x201, x198);
  fiat_p_addcarryx_u64(&x204, &x205, x203, x199, x196);
  fiat_p_addcarryx_u64(&x206, &x207, x205, x197, x194);
  fiat_p_addcarryx_u64(&x208, &x209, x207, x195, x192);
  fiat_p_addcarryx_u64(&x210, &x211, 0x0, x182, x200);
  fiat_p_addcarryx_u64(&x212, &x213, x211, x184, x202);
  fiat_p_addcarryx_u64(&x214, &x215, x213, x186, x204);
  fiat_p_addcarryx_u64(&x216, &x217, x215, x188, x206);
  fiat_p_addcarryx_u64(&x218, &x219, x217, x190, x208);
  fiat_p_mulx_u64(&x220, &x221, x4, UINT64_C(0x16e25bb319));
  fiat_p_mulx_u64(&x222, &x223, x4, UINT64_C(0xc4090ace285ae4b));
  fiat_p_mulx_u64(&x224, &x225, x4, UINT64_C(0x436d462f60fe53fc));
  fiat_p_mulx_u64(&x226, &x227, x4, UINT64_C(0x3cccfaf93709ad2f));
  fiat_p_mulx_u64(&x228, &x229, x4, UINT64_C(0x54c8f86fdde71429));
  fiat_p_addcarryx_u64(&x230, &x231, 0x0, x229, x226);
  fiat_p_addcarryx_u64(&x232, &x233, x231, x227, x224);
  fiat_p_addcarryx_u64(&x234, &x235, x233, x225, x222);
  fiat_p_addcarryx_u64(&x236, &x237, x235, x223, x220);
  fiat_p_addcarryx_u64(&x238, &x239, 0x0, x212, x228);
  fiat_p_addcarryx_u64(&x240, &x241, x239, x214, x230);
  fiat_p_addcarryx_u64(&x242, &x243, x241, x216, x232);
  fiat_p_addcarryx_u64(&x244, &x245, x243, x218, x234);
  fiat_p_addcarryx_u64(&x246, &x247, x245, ((x219 + (x191 + (x181 + x165))) + (x209 + x193)), x236);
  fiat_p_mulx_u64(&x248, &x249, x238, UINT64_C(0x1ae2e77fe01));
  fiat_p_mulx_u64(&x250, &x251, x238, UINT64_C(0xe2639b854da79fe3));
  fiat_p_mulx_u64(&x252, &x253, x238, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x254, &x255, x238, UINT64_C(0xffffffffffffffff));
  fiat_p_mulx_u64(&x256, &x257, x238, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x258, &x259, 0x0, x257, x254);
  fiat_p_addcarryx_u64(&x260, &x261, x259, x255, x252);
  fiat_p_addcarryx_u64(&x262, &x263, x261, x253, x250);
  fiat_p_addcarryx_u64(&x264, &x265, x263, x251, x248);
  fiat_p_addcarryx_u64(&x266, &x267, 0x0, x238, x256);
  fiat_p_addcarryx_u64(&x268, &x269, x267, x240, x258);
  fiat_p_addcarryx_u64(&x270, &x271, x269, x242, x260);
  fiat_p_addcarryx_u64(&x272, &x273, x271, x244, x262);
  fiat_p_addcarryx_u64(&x274, &x275, x273, x246, x264);
  x276 = ((x275 + (x247 + (x237 + x221))) + (x265 + x249));
  fiat_p_subborrowx_u64(&x277, &x278, 0x0, x268, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x279, &x280, x278, x270, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x281, &x282, x280, x272, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x283, &x284, x282, x274, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x285, &x286, x284, x276, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x287, &x288, x286, 0x0, 0x0);
  fiat_p_cmovznz_u64(&x289, x288, x277, x268);
  fiat_p_cmovznz_u64(&x290, x288, x279, x270);
  fiat_p_cmovznz_u64(&x291, x288, x281, x272);
  fiat_p_cmovznz_u64(&x292, x288, x283, x274);
  fiat_p_cmovznz_u64(&x293, x288, x285, x276);
  out1[0] = x289;
  out1[1] = x290;
  out1[2] = x291;
  out1[3] = x292;
  out1[4] = x293;
}

/*
 * The function fiat_p_nonzero outputs a single non-zero word if the input is non-zero and zero otherwise.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = 0 ↔ eval (from_montgomery arg1) mod m = 0
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
void fiat_p_nonzero(uint64_t* out1, const uint64_t arg1[5]) {
  uint64_t x1;
  x1 = ((arg1[0]) | ((arg1[1]) | ((arg1[2]) | ((arg1[3]) | (arg1[4])))));
  *out1 = x1;
}

/*
 * The function fiat_p_selectznz is a multi-limb conditional select.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_p_selectznz(uint64_t out1[5], fiat_p_uint1 arg1, const uint64_t arg2[5], const uint64_t arg3[5]) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  fiat_p_cmovznz_u64(&x1, arg1, (arg2[0]), (arg3[0]));
  fiat_p_cmovznz_u64(&x2, arg1, (arg2[1]), (arg3[1]));
  fiat_p_cmovznz_u64(&x3, arg1, (arg2[2]), (arg3[2]));
  fiat_p_cmovznz_u64(&x4, arg1, (arg2[3]), (arg3[3]));
  fiat_p_cmovznz_u64(&x5, arg1, (arg2[4]), (arg3[4]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
  out1[3] = x4;
  out1[4] = x5;
}

/*
 * The function fiat_p_to_bytes serializes a field element NOT in the Montgomery domain to bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..37]
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0x1ffffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x1]]
 */
void fiat_p_to_bytes(uint8_t out1[38], const uint64_t arg1[5]) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint8_t x6;
  uint64_t x7;
  uint8_t x8;
  uint64_t x9;
  uint8_t x10;
  uint64_t x11;
  uint8_t x12;
  uint64_t x13;
  uint8_t x14;
  uint64_t x15;
  uint8_t x16;
  uint64_t x17;
  uint8_t x18;
  uint8_t x19;
  uint8_t x20;
  uint64_t x21;
  uint8_t x22;
  uint64_t x23;
  uint8_t x24;
  uint64_t x25;
  uint8_t x26;
  uint64_t x27;
  uint8_t x28;
  uint64_t x29;
  uint8_t x30;
  uint64_t x31;
  uint8_t x32;
  uint8_t x33;
  uint8_t x34;
  uint64_t x35;
  uint8_t x36;
  uint64_t x37;
  uint8_t x38;
  uint64_t x39;
  uint8_t x40;
  uint64_t x41;
  uint8_t x42;
  uint64_t x43;
  uint8_t x44;
  uint64_t x45;
  uint8_t x46;
  uint8_t x47;
  uint8_t x48;
  uint64_t x49;
  uint8_t x50;
  uint64_t x51;
  uint8_t x52;
  uint64_t x53;
  uint8_t x54;
  uint64_t x55;
  uint8_t x56;
  uint64_t x57;
  uint8_t x58;
  uint64_t x59;
  uint8_t x60;
  uint8_t x61;
  uint8_t x62;
  uint64_t x63;
  uint8_t x64;
  uint64_t x65;
  uint8_t x66;
  uint64_t x67;
  uint8_t x68;
  uint64_t x69;
  uint8_t x70;
  fiat_p_uint1 x71;
  x1 = (arg1[4]);
  x2 = (arg1[3]);
  x3 = (arg1[2]);
  x4 = (arg1[1]);
  x5 = (arg1[0]);
  x6 = (uint8_t)(x5 & UINT8_C(0xff));
  x7 = (x5 >> 8);
  x8 = (uint8_t)(x7 & UINT8_C(0xff));
  x9 = (x7 >> 8);
  x10 = (uint8_t)(x9 & UINT8_C(0xff));
  x11 = (x9 >> 8);
  x12 = (uint8_t)(x11 & UINT8_C(0xff));
  x13 = (x11 >> 8);
  x14 = (uint8_t)(x13 & UINT8_C(0xff));
  x15 = (x13 >> 8);
  x16 = (uint8_t)(x15 & UINT8_C(0xff));
  x17 = (x15 >> 8);
  x18 = (uint8_t)(x17 & UINT8_C(0xff));
  x19 = (uint8_t)(x17 >> 8);
  x20 = (uint8_t)(x4 & UINT8_C(0xff));
  x21 = (x4 >> 8);
  x22 = (uint8_t)(x21 & UINT8_C(0xff));
  x23 = (x21 >> 8);
  x24 = (uint8_t)(x23 & UINT8_C(0xff));
  x25 = (x23 >> 8);
  x26 = (uint8_t)(x25 & UINT8_C(0xff));
  x27 = (x25 >> 8);
  x28 = (uint8_t)(x27 & UINT8_C(0xff));
  x29 = (x27 >> 8);
  x30 = (uint8_t)(x29 & UINT8_C(0xff));
  x31 = (x29 >> 8);
  x32 = (uint8_t)(x31 & UINT8_C(0xff));
  x33 = (uint8_t)(x31 >> 8);
  x34 = (uint8_t)(x3 & UINT8_C(0xff));
  x35 = (x3 >> 8);
  x36 = (uint8_t)(x35 & UINT8_C(0xff));
  x37 = (x35 >> 8);
  x38 = (uint8_t)(x37 & UINT8_C(0xff));
  x39 = (x37 >> 8);
  x40 = (uint8_t)(x39 & UINT8_C(0xff));
  x41 = (x39 >> 8);
  x42 = (uint8_t)(x41 & UINT8_C(0xff));
  x43 = (x41 >> 8);
  x44 = (uint8_t)(x43 & UINT8_C(0xff));
  x45 = (x43 >> 8);
  x46 = (uint8_t)(x45 & UINT8_C(0xff));
  x47 = (uint8_t)(x45 >> 8);
  x48 = (uint8_t)(x2 & UINT8_C(0xff));
  x49 = (x2 >> 8);
  x50 = (uint8_t)(x49 & UINT8_C(0xff));
  x51 = (x49 >> 8);
  x52 = (uint8_t)(x51 & UINT8_C(0xff));
  x53 = (x51 >> 8);
  x54 = (uint8_t)(x53 & UINT8_C(0xff));
  x55 = (x53 >> 8);
  x56 = (uint8_t)(x55 & UINT8_C(0xff));
  x57 = (x55 >> 8);
  x58 = (uint8_t)(x57 & UINT8_C(0xff));
  x59 = (x57 >> 8);
  x60 = (uint8_t)(x59 & UINT8_C(0xff));
  x61 = (uint8_t)(x59 >> 8);
  x62 = (uint8_t)(x1 & UINT8_C(0xff));
  x63 = (x1 >> 8);
  x64 = (uint8_t)(x63 & UINT8_C(0xff));
  x65 = (x63 >> 8);
  x66 = (uint8_t)(x65 & UINT8_C(0xff));
  x67 = (x65 >> 8);
  x68 = (uint8_t)(x67 & UINT8_C(0xff));
  x69 = (x67 >> 8);
  x70 = (uint8_t)(x69 & UINT8_C(0xff));
  x71 = (fiat_p_uint1)(x69 >> 8);
  out1[0] = x6;
  out1[1] = x8;
  out1[2] = x10;
  out1[3] = x12;
  out1[4] = x14;
  out1[5] = x16;
  out1[6] = x18;
  out1[7] = x19;
  out1[8] = x20;
  out1[9] = x22;
  out1[10] = x24;
  out1[11] = x26;
  out1[12] = x28;
  out1[13] = x30;
  out1[14] = x32;
  out1[15] = x33;
  out1[16] = x34;
  out1[17] = x36;
  out1[18] = x38;
  out1[19] = x40;
  out1[20] = x42;
  out1[21] = x44;
  out1[22] = x46;
  out1[23] = x47;
  out1[24] = x48;
  out1[25] = x50;
  out1[26] = x52;
  out1[27] = x54;
  out1[28] = x56;
  out1[29] = x58;
  out1[30] = x60;
  out1[31] = x61;
  out1[32] = x62;
  out1[33] = x64;
  out1[34] = x66;
  out1[35] = x68;
  out1[36] = x70;
  out1[37] = x71;
}

/*
 * The function fiat_p_from_bytes deserializes a field element NOT in the Montgomery domain from bytes in little-endian order.
 *
 * Preconditions:
 *   0 ≤ bytes_eval arg1 < m
 * Postconditions:
 *   eval out1 mod m = bytes_eval arg1 mod m
 *   0 ≤ eval out1 < m
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x1]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0x1ffffffffff]]
 */
void fiat_p_from_bytes(uint64_t out1[5], const uint8_t arg1[38]) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint8_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint8_t x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  uint64_t x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  uint8_t x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint8_t x30;
  uint64_t x31;
  uint64_t x32;
  uint64_t x33;
  uint64_t x34;
  uint64_t x35;
  uint64_t x36;
  uint64_t x37;
  uint8_t x38;
  uint64_t x39;
  uint64_t x40;
  uint64_t x41;
  uint64_t x42;
  uint64_t x43;
  uint64_t x44;
  uint64_t x45;
  uint64_t x46;
  uint64_t x47;
  uint64_t x48;
  uint64_t x49;
  uint64_t x50;
  uint64_t x51;
  uint64_t x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  uint64_t x56;
  uint64_t x57;
  uint64_t x58;
  uint64_t x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  uint64_t x63;
  uint64_t x64;
  uint64_t x65;
  uint64_t x66;
  uint64_t x67;
  uint64_t x68;
  uint64_t x69;
  uint64_t x70;
  uint64_t x71;
  x1 = ((uint64_t)(fiat_p_uint1)(arg1[37]) << 40);
  x2 = ((uint64_t)(arg1[36]) << 32);
  x3 = ((uint64_t)(arg1[35]) << 24);
  x4 = ((uint64_t)(arg1[34]) << 16);
  x5 = ((uint64_t)(arg1[33]) << 8);
  x6 = (arg1[32]);
  x7 = ((uint64_t)(arg1[31]) << 56);
  x8 = ((uint64_t)(arg1[30]) << 48);
  x9 = ((uint64_t)(arg1[29]) << 40);
  x10 = ((uint64_t)(arg1[28]) << 32);
  x11 = ((uint64_t)(arg1[27]) << 24);
  x12 = ((uint64_t)(arg1[26]) << 16);
  x13 = ((uint64_t)(arg1[25]) << 8);
  x14 = (arg1[24]);
  x15 = ((uint64_t)(arg1[23]) << 56);
  x16 = ((uint64_t)(arg1[22]) << 48);
  x17 = ((uint64_t)(arg1[21]) << 40);
  x18 = ((uint64_t)(arg1[20]) << 32);
  x19 = ((uint64_t)(arg1[19]) << 24);
  x20 = ((uint64_t)(arg1[18]) << 16);
  x21 = ((uint64_t)(arg1[17]) << 8);
  x22 = (arg1[16]);
  x23 = ((uint64_t)(arg1[15]) << 56);
  x24 = ((uint64_t)(arg1[14]) << 48);
  x25 = ((uint64_t)(arg1[13]) << 40);
  x26 = ((uint64_t)(arg1[12]) << 32);
  x27 = ((uint64_t)(arg1[11]) << 24);
  x28 = ((uint64_t)(arg1[10]) << 16);
  x29 = ((uint64_t)(arg1[9]) << 8);
  x30 = (arg1[8]);
  x31 = ((uint64_t)(arg1[7]) << 56);
  x32 = ((uint64_t)(arg1[6]) << 48);
  x33 = ((uint64_t)(arg1[5]) << 40);
  x34 = ((uint64_t)(arg1[4]) << 32);
  x35 = ((uint64_t)(arg1[3]) << 24);
  x36 = ((uint64_t)(arg1[2]) << 16);
  x37 = ((uint64_t)(arg1[1]) << 8);
  x38 = (arg1[0]);
  x39 = (x37 + (uint64_t)x38);
  x40 = (x36 + x39);
  x41 = (x35 + x40);
  x42 = (x34 + x41);
  x43 = (x33 + x42);
  x44 = (x32 + x43);
  x45 = (x31 + x44);
  x46 = (x29 + (uint64_t)x30);
  x47 = (x28 + x46);
  x48 = (x27 + x47);
  x49 = (x26 + x48);
  x50 = (x25 + x49);
  x51 = (x24 + x50);
  x52 = (x23 + x51);
  x53 = (x21 + (uint64_t)x22);
  x54 = (x20 + x53);
  x55 = (x19 + x54);
  x56 = (x18 + x55);
  x57 = (x17 + x56);
  x58 = (x16 + x57);
  x59 = (x15 + x58);
  x60 = (x13 + (uint64_t)x14);
  x61 = (x12 + x60);
  x62 = (x11 + x61);
  x63 = (x10 + x62);
  x64 = (x9 + x63);
  x65 = (x8 + x64);
  x66 = (x7 + x65);
  x67 = (x5 + (uint64_t)x6);
  x68 = (x4 + x67);
  x69 = (x3 + x68);
  x70 = (x2 + x69);
  x71 = (x1 + x70);
  out1[0] = x45;
  out1[1] = x52;
  out1[2] = x59;
  out1[3] = x66;
  out1[4] = x71;
}

/*
 * The function fiat_p_set_one returns the field element one in the Montgomery domain.
 *
 * Postconditions:
 *   eval (from_montgomery out1) mod m = 1 mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_p_set_one(fiat_p_montgomery_domain_field_element out1) {
  out1[0] = UINT32_C(0x985851);
  out1[1] = 0x0;
  out1[2] = 0x0;
  out1[3] = UINT64_C(0xc9dfdc99dfa008dc);
  out1[4] = UINT64_C(0xab3b999070);
}

/*
 * The function fiat_p_msat returns the saturated representation of the prime modulus.
 *
 * Postconditions:
 *   twos_complement_eval out1 = m
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_p_msat(uint64_t out1[6]) {
  out1[0] = UINT64_C(0xffffffffffffffff);
  out1[1] = UINT64_C(0xffffffffffffffff);
  out1[2] = UINT64_C(0xffffffffffffffff);
  out1[3] = UINT64_C(0xe2639b854da79fe3);
  out1[4] = UINT64_C(0x1ae2e77fe01);
  out1[5] = 0x0;
}

/*
 * The function fiat_p_divstep_precomp returns the precomputed value for Bernstein-Yang-inversion (in montgomery form).
 *
 * Postconditions:
 *   eval (from_montgomery out1) = ⌊(m - 1) / 2⌋^(if ⌊log2 m⌋ + 1 < 46 then ⌊(49 * (⌊log2 m⌋ + 1) + 80) / 17⌋ else ⌊(49 * (⌊log2 m⌋ + 1) + 57) / 17⌋)
 *   0 ≤ eval out1 < m
 *
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_p_divstep_precomp(uint64_t out1[5]) {
  out1[0] = UINT64_C(0x820fa4047114bb6a);
  out1[1] = UINT64_C(0xd261f5af58b50b4);
  out1[2] = UINT64_C(0xd647d5d43a794dcc);
  out1[3] = UINT64_C(0x41f3178a9406e48c);
  out1[4] = UINT64_C(0x135b5a3a238);
}

/*
 * The function fiat_p_divstep computes a divstep.
 *
 * Preconditions:
 *   0 ≤ eval arg4 < m
 *   0 ≤ eval arg5 < m
 * Postconditions:
 *   out1 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then 1 - arg1 else 1 + arg1)
 *   twos_complement_eval out2 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then twos_complement_eval arg3 else twos_complement_eval arg2)
 *   twos_complement_eval out3 = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then ⌊(twos_complement_eval arg3 - twos_complement_eval arg2) / 2⌋ else ⌊(twos_complement_eval arg3 + (twos_complement_eval arg3 mod 2) * twos_complement_eval arg2) / 2⌋)
 *   eval (from_montgomery out4) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (2 * eval (from_montgomery arg5)) mod m else (2 * eval (from_montgomery arg4)) mod m)
 *   eval (from_montgomery out5) mod m = (if 0 < arg1 ∧ (twos_complement_eval arg3) is odd then (eval (from_montgomery arg4) - eval (from_montgomery arg4)) mod m else (eval (from_montgomery arg5) + (twos_complement_eval arg3 mod 2) * eval (from_montgomery arg4)) mod m)
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out5 < m
 *   0 ≤ eval out2 < m
 *   0 ≤ eval out3 < m
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   arg5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out4: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 *   out5: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_p_divstep(uint64_t* out1, uint64_t out2[6], uint64_t out3[6], uint64_t out4[5], uint64_t out5[5], uint64_t arg1, const uint64_t arg2[6], const uint64_t arg3[6], const uint64_t arg4[5], const uint64_t arg5[5]) {
  uint64_t x1;
  fiat_p_uint1 x2;
  fiat_p_uint1 x3;
  uint64_t x4;
  fiat_p_uint1 x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  fiat_p_uint1 x14;
  uint64_t x15;
  fiat_p_uint1 x16;
  uint64_t x17;
  fiat_p_uint1 x18;
  uint64_t x19;
  fiat_p_uint1 x20;
  uint64_t x21;
  fiat_p_uint1 x22;
  uint64_t x23;
  fiat_p_uint1 x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  uint64_t x31;
  uint64_t x32;
  uint64_t x33;
  uint64_t x34;
  uint64_t x35;
  uint64_t x36;
  fiat_p_uint1 x37;
  uint64_t x38;
  fiat_p_uint1 x39;
  uint64_t x40;
  fiat_p_uint1 x41;
  uint64_t x42;
  fiat_p_uint1 x43;
  uint64_t x44;
  fiat_p_uint1 x45;
  uint64_t x46;
  fiat_p_uint1 x47;
  uint64_t x48;
  fiat_p_uint1 x49;
  uint64_t x50;
  fiat_p_uint1 x51;
  uint64_t x52;
  fiat_p_uint1 x53;
  uint64_t x54;
  fiat_p_uint1 x55;
  uint64_t x56;
  fiat_p_uint1 x57;
  uint64_t x58;
  uint64_t x59;
  uint64_t x60;
  uint64_t x61;
  uint64_t x62;
  uint64_t x63;
  fiat_p_uint1 x64;
  uint64_t x65;
  fiat_p_uint1 x66;
  uint64_t x67;
  fiat_p_uint1 x68;
  uint64_t x69;
  fiat_p_uint1 x70;
  uint64_t x71;
  fiat_p_uint1 x72;
  uint64_t x73;
  uint64_t x74;
  fiat_p_uint1 x75;
  uint64_t x76;
  fiat_p_uint1 x77;
  uint64_t x78;
  fiat_p_uint1 x79;
  uint64_t x80;
  fiat_p_uint1 x81;
  uint64_t x82;
  fiat_p_uint1 x83;
  uint64_t x84;
  uint64_t x85;
  uint64_t x86;
  uint64_t x87;
  uint64_t x88;
  fiat_p_uint1 x89;
  uint64_t x90;
  uint64_t x91;
  uint64_t x92;
  uint64_t x93;
  uint64_t x94;
  uint64_t x95;
  uint64_t x96;
  fiat_p_uint1 x97;
  uint64_t x98;
  fiat_p_uint1 x99;
  uint64_t x100;
  fiat_p_uint1 x101;
  uint64_t x102;
  fiat_p_uint1 x103;
  uint64_t x104;
  fiat_p_uint1 x105;
  uint64_t x106;
  fiat_p_uint1 x107;
  uint64_t x108;
  uint64_t x109;
  uint64_t x110;
  uint64_t x111;
  uint64_t x112;
  uint64_t x113;
  fiat_p_uint1 x114;
  uint64_t x115;
  fiat_p_uint1 x116;
  uint64_t x117;
  fiat_p_uint1 x118;
  uint64_t x119;
  fiat_p_uint1 x120;
  uint64_t x121;
  fiat_p_uint1 x122;
  uint64_t x123;
  fiat_p_uint1 x124;
  uint64_t x125;
  fiat_p_uint1 x126;
  uint64_t x127;
  fiat_p_uint1 x128;
  uint64_t x129;
  fiat_p_uint1 x130;
  uint64_t x131;
  fiat_p_uint1 x132;
  uint64_t x133;
  fiat_p_uint1 x134;
  uint64_t x135;
  fiat_p_uint1 x136;
  uint64_t x137;
  uint64_t x138;
  uint64_t x139;
  uint64_t x140;
  uint64_t x141;
  uint64_t x142;
  uint64_t x143;
  uint64_t x144;
  uint64_t x145;
  uint64_t x146;
  uint64_t x147;
  uint64_t x148;
  uint64_t x149;
  uint64_t x150;
  uint64_t x151;
  uint64_t x152;
  fiat_p_addcarryx_u64(&x1, &x2, 0x0, (~arg1), 0x1);
  x3 = (fiat_p_uint1)((fiat_p_uint1)(x1 >> 63) & (fiat_p_uint1)((arg3[0]) & 0x1));
  fiat_p_addcarryx_u64(&x4, &x5, 0x0, (~arg1), 0x1);
  fiat_p_cmovznz_u64(&x6, x3, arg1, x4);
  fiat_p_cmovznz_u64(&x7, x3, (arg2[0]), (arg3[0]));
  fiat_p_cmovznz_u64(&x8, x3, (arg2[1]), (arg3[1]));
  fiat_p_cmovznz_u64(&x9, x3, (arg2[2]), (arg3[2]));
  fiat_p_cmovznz_u64(&x10, x3, (arg2[3]), (arg3[3]));
  fiat_p_cmovznz_u64(&x11, x3, (arg2[4]), (arg3[4]));
  fiat_p_cmovznz_u64(&x12, x3, (arg2[5]), (arg3[5]));
  fiat_p_addcarryx_u64(&x13, &x14, 0x0, 0x1, (~(arg2[0])));
  fiat_p_addcarryx_u64(&x15, &x16, x14, 0x0, (~(arg2[1])));
  fiat_p_addcarryx_u64(&x17, &x18, x16, 0x0, (~(arg2[2])));
  fiat_p_addcarryx_u64(&x19, &x20, x18, 0x0, (~(arg2[3])));
  fiat_p_addcarryx_u64(&x21, &x22, x20, 0x0, (~(arg2[4])));
  fiat_p_addcarryx_u64(&x23, &x24, x22, 0x0, (~(arg2[5])));
  fiat_p_cmovznz_u64(&x25, x3, (arg3[0]), x13);
  fiat_p_cmovznz_u64(&x26, x3, (arg3[1]), x15);
  fiat_p_cmovznz_u64(&x27, x3, (arg3[2]), x17);
  fiat_p_cmovznz_u64(&x28, x3, (arg3[3]), x19);
  fiat_p_cmovznz_u64(&x29, x3, (arg3[4]), x21);
  fiat_p_cmovznz_u64(&x30, x3, (arg3[5]), x23);
  fiat_p_cmovznz_u64(&x31, x3, (arg4[0]), (arg5[0]));
  fiat_p_cmovznz_u64(&x32, x3, (arg4[1]), (arg5[1]));
  fiat_p_cmovznz_u64(&x33, x3, (arg4[2]), (arg5[2]));
  fiat_p_cmovznz_u64(&x34, x3, (arg4[3]), (arg5[3]));
  fiat_p_cmovznz_u64(&x35, x3, (arg4[4]), (arg5[4]));
  fiat_p_addcarryx_u64(&x36, &x37, 0x0, x31, x31);
  fiat_p_addcarryx_u64(&x38, &x39, x37, x32, x32);
  fiat_p_addcarryx_u64(&x40, &x41, x39, x33, x33);
  fiat_p_addcarryx_u64(&x42, &x43, x41, x34, x34);
  fiat_p_addcarryx_u64(&x44, &x45, x43, x35, x35);
  fiat_p_subborrowx_u64(&x46, &x47, 0x0, x36, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x48, &x49, x47, x38, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x50, &x51, x49, x40, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x52, &x53, x51, x42, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x54, &x55, x53, x44, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x56, &x57, x55, x45, 0x0);
  x58 = (arg4[4]);
  x59 = (arg4[3]);
  x60 = (arg4[2]);
  x61 = (arg4[1]);
  x62 = (arg4[0]);
  fiat_p_subborrowx_u64(&x63, &x64, 0x0, 0x0, x62);
  fiat_p_subborrowx_u64(&x65, &x66, x64, 0x0, x61);
  fiat_p_subborrowx_u64(&x67, &x68, x66, 0x0, x60);
  fiat_p_subborrowx_u64(&x69, &x70, x68, 0x0, x59);
  fiat_p_subborrowx_u64(&x71, &x72, x70, 0x0, x58);
  fiat_p_cmovznz_u64(&x73, x72, 0x0, UINT64_C(0xffffffffffffffff));
  fiat_p_addcarryx_u64(&x74, &x75, 0x0, x63, x73);
  fiat_p_addcarryx_u64(&x76, &x77, x75, x65, x73);
  fiat_p_addcarryx_u64(&x78, &x79, x77, x67, x73);
  fiat_p_addcarryx_u64(&x80, &x81, x79, x69, (x73 & UINT64_C(0xe2639b854da79fe3)));
  fiat_p_addcarryx_u64(&x82, &x83, x81, x71, (x73 & UINT64_C(0x1ae2e77fe01)));
  fiat_p_cmovznz_u64(&x84, x3, (arg5[0]), x74);
  fiat_p_cmovznz_u64(&x85, x3, (arg5[1]), x76);
  fiat_p_cmovznz_u64(&x86, x3, (arg5[2]), x78);
  fiat_p_cmovznz_u64(&x87, x3, (arg5[3]), x80);
  fiat_p_cmovznz_u64(&x88, x3, (arg5[4]), x82);
  x89 = (fiat_p_uint1)(x25 & 0x1);
  fiat_p_cmovznz_u64(&x90, x89, 0x0, x7);
  fiat_p_cmovznz_u64(&x91, x89, 0x0, x8);
  fiat_p_cmovznz_u64(&x92, x89, 0x0, x9);
  fiat_p_cmovznz_u64(&x93, x89, 0x0, x10);
  fiat_p_cmovznz_u64(&x94, x89, 0x0, x11);
  fiat_p_cmovznz_u64(&x95, x89, 0x0, x12);
  fiat_p_addcarryx_u64(&x96, &x97, 0x0, x25, x90);
  fiat_p_addcarryx_u64(&x98, &x99, x97, x26, x91);
  fiat_p_addcarryx_u64(&x100, &x101, x99, x27, x92);
  fiat_p_addcarryx_u64(&x102, &x103, x101, x28, x93);
  fiat_p_addcarryx_u64(&x104, &x105, x103, x29, x94);
  fiat_p_addcarryx_u64(&x106, &x107, x105, x30, x95);
  fiat_p_cmovznz_u64(&x108, x89, 0x0, x31);
  fiat_p_cmovznz_u64(&x109, x89, 0x0, x32);
  fiat_p_cmovznz_u64(&x110, x89, 0x0, x33);
  fiat_p_cmovznz_u64(&x111, x89, 0x0, x34);
  fiat_p_cmovznz_u64(&x112, x89, 0x0, x35);
  fiat_p_addcarryx_u64(&x113, &x114, 0x0, x84, x108);
  fiat_p_addcarryx_u64(&x115, &x116, x114, x85, x109);
  fiat_p_addcarryx_u64(&x117, &x118, x116, x86, x110);
  fiat_p_addcarryx_u64(&x119, &x120, x118, x87, x111);
  fiat_p_addcarryx_u64(&x121, &x122, x120, x88, x112);
  fiat_p_subborrowx_u64(&x123, &x124, 0x0, x113, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x125, &x126, x124, x115, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x127, &x128, x126, x117, UINT64_C(0xffffffffffffffff));
  fiat_p_subborrowx_u64(&x129, &x130, x128, x119, UINT64_C(0xe2639b854da79fe3));
  fiat_p_subborrowx_u64(&x131, &x132, x130, x121, UINT64_C(0x1ae2e77fe01));
  fiat_p_subborrowx_u64(&x133, &x134, x132, x122, 0x0);
  fiat_p_addcarryx_u64(&x135, &x136, 0x0, x6, 0x1);
  x137 = ((x96 >> 1) | ((x98 << 63) & UINT64_C(0xffffffffffffffff)));
  x138 = ((x98 >> 1) | ((x100 << 63) & UINT64_C(0xffffffffffffffff)));
  x139 = ((x100 >> 1) | ((x102 << 63) & UINT64_C(0xffffffffffffffff)));
  x140 = ((x102 >> 1) | ((x104 << 63) & UINT64_C(0xffffffffffffffff)));
  x141 = ((x104 >> 1) | ((x106 << 63) & UINT64_C(0xffffffffffffffff)));
  x142 = ((x106 & UINT64_C(0x8000000000000000)) | (x106 >> 1));
  fiat_p_cmovznz_u64(&x143, x57, x46, x36);
  fiat_p_cmovznz_u64(&x144, x57, x48, x38);
  fiat_p_cmovznz_u64(&x145, x57, x50, x40);
  fiat_p_cmovznz_u64(&x146, x57, x52, x42);
  fiat_p_cmovznz_u64(&x147, x57, x54, x44);
  fiat_p_cmovznz_u64(&x148, x134, x123, x113);
  fiat_p_cmovznz_u64(&x149, x134, x125, x115);
  fiat_p_cmovznz_u64(&x150, x134, x127, x117);
  fiat_p_cmovznz_u64(&x151, x134, x129, x119);
  fiat_p_cmovznz_u64(&x152, x134, x131, x121);
  *out1 = x135;
  out2[0] = x7;
  out2[1] = x8;
  out2[2] = x9;
  out2[3] = x10;
  out2[4] = x11;
  out2[5] = x12;
  out3[0] = x137;
  out3[1] = x138;
  out3[2] = x139;
  out3[3] = x140;
  out3[4] = x141;
  out3[5] = x142;
  out4[0] = x143;
  out4[1] = x144;
  out4[2] = x145;
  out4[3] = x146;
  out4[4] = x147;
  out5[0] = x148;
  out5[1] = x149;
  out5[2] = x150;
  out5[3] = x151;
  out5[4] = x152;
}

void fp_add(uint64_t* out, const uint64_t* a, const uint64_t* b) {
    fiat_p_add(out, a, b);
}

void fp_sub(uint64_t* out, const uint64_t* a, const uint64_t* b) {
    fiat_p_sub(out, a, b);
}

void fp_sqr(uint64_t* out, const uint64_t* a) {
    fiat_p_square(out, a);
}

void fp_mul(uint64_t* out, const uint64_t* a, const uint64_t* b) {
    fiat_p_mul(out, a, b);
}

void fp_tomont(uint64_t* out, const uint64_t* a) {
    fiat_p_to_montgomery(out, a);
}

void fp_frommont(uint64_t* out, const uint64_t* a) {
    fiat_p_from_montgomery(out, a);
}

void fp_mont_setone(uint64_t* out) {
    fiat_p_set_one(out);
}
